export const images = {
  loginBanner:
    'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80',
  roleIndividual:
    'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400&q=80',
  roleContractor:
    'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&q=80',
  roleInterior:
    'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=400&q=80',
  roleBuilder:
    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&q=80',
  emergencyBanner:
    'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80',
  deliveryTruck:
    'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&q=80',
  categoryCement: require('../assets/category-cement.png'),
  categoryRmc: require('../assets/category-rmc.png'),
  /** @deprecated Use categoryRmc — kept as alias for legacy imports */
  categorySteel: require('../assets/category-rmc.png'),
  categoryStone: require('../assets/category-stone-chips.png'),
  categorySand: require('../assets/category-sand.png'),
  categoryBricks: require('../assets/category-bricks.png'),
  categoryGreyFillSand: require('../assets/category-grey-fill-sand.png'),
  categoryAggregates: require('../assets/category-aggregates.png'),
  categoryAdhesives: require('../assets/category-adhesives.png'),
  categoryWallRepair: require('../assets/category-wall-repair.png'),
  categoryWaterproofing: require('../assets/category-waterproofing.png'),
  categoryQuickRepair: require('../assets/category-quick-repair.png'),
  categoryPutty: require('../assets/category-putty.png'),
  productUltratech: require('../assets/product-ultratech.png'),
  productUltratechBags: require('../assets/product-ultratech-bags.png'),
  productJswNeosteel: require('../assets/product-jsw-neosteel.png'),
  productAcc: require('../assets/product-acc.png'),
  productCrushedStoneAggregate: require('../assets/product-crushed-stone-aggregate.png'),
  productJeeraRodi: require('../assets/product-jeera-rodi.png'),
  productFevicolMarine: require('../assets/product-fevicol-marine.png'),
  productFevicolSh: require('../assets/product-fevicol-sh.png'),
  productFevicolProBond: require('../assets/product-fevicol-pro-bond.png'),
  productFevicolSr998: require('../assets/product-fevicol-sr998.png'),
  productFevicolHeatx: require('../assets/product-fevicol-heatx.png'),
  productFevicolSpeedx: require('../assets/product-fevicol-speedx.png'),
  productJivantor: require('../assets/product-jivantor.png'),
  productJkWallPutty: require('../assets/product-jk-wall-putty.png'),
  productBirlaPutty: require('../assets/product-birla-putty.png'),
  productSakarniPop: require('../assets/product-sakarni-pop.png'),
  productWhiteCement: require('../assets/product-white-cement.png'),
  productDrFixit301: require('../assets/product-dr-fixit-301.png'),
  productDrFixit302: require('../assets/product-dr-fixit-302.png'),
  productDrFixitSureSeal: require('../assets/product-dr-fixit-sure-seal.png'),
  productDrFixitAllSeal: require('../assets/product-dr-fixit-all-seal.png'),
  productDrFixit101Lw: require('../assets/product-dr-fixit-101-lw.png'),
  productDrFixit202Crackx: require('../assets/product-dr-fixit-202-crackx.png'),
  productPolyfix: require('../assets/product-polyfix.png'),
  productAraldite: require('../assets/product-araldite.png'),
  productFevikwik: require('../assets/product-fevikwik.png'),
  productAsianPaintsAcrylicPutty: require('../assets/product-asian-paints-acrylic-putty.png'),
  productGreyFlashCementBricks: require('../assets/product-grey-flash-cement-bricks.png'),
  productGreyAshBricksAPlus: require('../assets/product-grey-ash-bricks-a-plus.png'),
  productGreyAshBricksBPlus: require('../assets/product-grey-ash-bricks-b-plus.png'),
  productRedBricks: require('../assets/product-red-bricks.png'),
  productRedBricksAPlus: require('../assets/product-red-bricks-a-plus.png'),
  productRedBricksBPlus: require('../assets/product-red-bricks-b-plus.png'),
  productTataTiscon500d: require('../assets/product-tata-tiscon-500d.png'),
  productRiverSand: require('../assets/product-river-sand.png'),
  productDust: require('../assets/product-dust.png'),
  product40mmCrushedStone: require('../assets/product-40mm-crushed-stone.png'),
  notificationProTip:
    'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
} as const;

/** Curated Unsplash URLs for SKU product images (source.unsplash.com is deprecated). */
export const productImageUrls = {
  cementBags: 'https://images.unsplash.com/photo-1565008576549-57569a49371d',
  cementSite: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5',
  mSand: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35',
  riverSand: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64',
  redBricks: 'https://images.unsplash.com/photo-1595846519845-68e298c2edd8',
  redBricksStack: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4',
  aacBlocks: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f',
  stoneAggregate: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86',
  crushedStone: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96',
  steelBars: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e',
  constructionSite: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd',
} as const;
