export interface CatalogVariant {
  id: string;
  label: string;
  displayUnit?: string;
  quantity?: number;
  count?: number;
  weight?: number;
  volume?: number;
  price: number;
  bulkPrice?: number | null;
}

export interface CatalogProduct {
  id: string;
  name: string;
  brand: string;
  category: string;
  categoryLabel: string;
  description: string;
  badge: string | null;
  status: string;
  imageQuery: string;
  images: string[];
  hasVariants: boolean;
  unit: string;
  unitLabel?: string;
  variants?: CatalogVariant[];
  defaultVariantId?: string;
  retailPrice?: number;
  bulkPrice?: number;
  bulkThreshold?: number;
  minOrder?: number;
  stepSize?: number;
  maxOrder?: number;
  perPiecePrice?: number;
  specs: Record<string, string>;
}

export const ALL_PRODUCTS: CatalogProduct[] = [
  {
    id: 'cement_001',
    name: 'Cement',
    brand: 'TBD',
    category: 'cement',
    categoryLabel: 'Cement',
    description: 'High-strength OPC 53 grade cement for structural construction.',
    badge: 'GET READY',
    status: 'IN STOCK',
    imageQuery: 'cement bag construction',
    images: [
      'https://source.unsplash.com/featured/600x400/?cement+bag',
      'https://source.unsplash.com/featured/600x400/?cement+construction',
    ],
    hasVariants: false,
    retailPrice: 425,
    bulkPrice: 398,
    bulkThreshold: 50,
    minOrder: 1,
    stepSize: 1,
    unit: 'Bag',
    unitLabel: 'Bag',
    maxOrder: 100,
    specs: {
      GRADE: '53 Grade OPC',
      'SETTING TIME': '30–600 mins',
      STRENGTH: 'Superior Durability',
      COMPRESSION: '27 MPa (3 Days)',
    },
  },
  {
    id: 'sand_dust',
    name: 'Dust',
    brand: 'Local',
    category: 'sand',
    categoryLabel: 'Sand',
    description: 'Fine dust sand for plastering, flooring, and construction use.',
    badge: null,
    status: 'IN STOCK',
    imageQuery: 'dust sand construction',
    images: [
      'https://source.unsplash.com/featured/600x400/?construction+sand',
      'https://source.unsplash.com/featured/600x400/?sand+pile',
    ],
    hasVariants: true,
    unit: 'CFT',
    unitLabel: 'CFT',
    variants: [
      { id: 'sd_10', label: '10 CFT', quantity: 10, price: 600, bulkPrice: null },
      { id: 'sd_20', label: '20 CFT', quantity: 20, price: 1150, bulkPrice: null },
      { id: 'sd_30', label: '30 CFT', quantity: 30, price: 1680, bulkPrice: null },
      { id: 'sd_40', label: '40 CFT', quantity: 40, price: 2200, bulkPrice: null },
      { id: 'sd_50', label: '50 CFT', quantity: 50, price: 2700, bulkPrice: null },
      { id: 'sd_60', label: '60 CFT', quantity: 60, price: 3180, bulkPrice: null },
      { id: 'sd_70', label: '70 CFT', quantity: 70, price: 3640, bulkPrice: null },
      { id: 'sd_80', label: '80 CFT', quantity: 80, price: 4080, bulkPrice: null },
      { id: 'sd_90', label: '90 CFT', quantity: 90, price: 4500, bulkPrice: null },
    ],
    defaultVariantId: 'sd_10',
    specs: {
      TYPE: 'Fine Dust',
      GRADE: 'Zone III',
      'SILT CONTENT': '<5%',
      USE: 'Plastering / Flooring',
    },
  },
  {
    id: 'sand_river',
    name: 'River Sand',
    brand: 'Natural',
    category: 'sand',
    categoryLabel: 'Sand',
    description: 'Premium river sand for concrete mixing and construction.',
    badge: 'POPULAR',
    status: 'IN STOCK',
    imageQuery: 'river sand construction',
    images: [
      'https://source.unsplash.com/featured/600x400/?river+sand',
      'https://source.unsplash.com/featured/600x400/?sand+construction',
    ],
    hasVariants: true,
    unit: 'CFT',
    unitLabel: 'CFT',
    variants: [
      { id: 'rs_10', label: '10 CFT', quantity: 10, price: 750, bulkPrice: null },
      { id: 'rs_20', label: '20 CFT', quantity: 20, price: 1450, bulkPrice: null },
      { id: 'rs_30', label: '30 CFT', quantity: 30, price: 2100, bulkPrice: null },
      { id: 'rs_40', label: '40 CFT', quantity: 40, price: 2750, bulkPrice: null },
      { id: 'rs_50', label: '50 CFT', quantity: 50, price: 3350, bulkPrice: null },
      { id: 'rs_60', label: '60 CFT', quantity: 60, price: 3900, bulkPrice: null },
      { id: 'rs_70', label: '70 CFT', quantity: 70, price: 4400, bulkPrice: null },
      { id: 'rs_80', label: '80 CFT', quantity: 80, price: 4850, bulkPrice: null },
      { id: 'rs_90', label: '90 CFT', quantity: 90, price: 5250, bulkPrice: null },
    ],
    defaultVariantId: 'rs_10',
    specs: {
      TYPE: 'River Sand',
      GRADE: 'Zone II',
      'SILT CONTENT': '<3%',
      USE: 'Concrete / RCC',
    },
  },
  {
    id: 'bricks_red',
    name: 'Red Bricks',
    brand: 'Regional Supplier',
    category: 'bricks',
    categoryLabel: 'Bricks',
    description: 'ISI standard red clay bricks for walls and construction.',
    badge: 'GET READY',
    status: 'IN STOCK',
    imageQuery: 'red bricks construction',
    images: [
      'https://source.unsplash.com/featured/600x400/?red+bricks',
      'https://source.unsplash.com/featured/600x400/?brick+wall+construction',
    ],
    hasVariants: true,
    unit: 'Pieces',
    unitLabel: 'Pieces',
    variants: [
      { id: 'rb_100', label: '100 Pieces', count: 100, price: 850, bulkPrice: null },
      { id: 'rb_200', label: '200 Pieces', count: 200, price: 1680, bulkPrice: null },
      { id: 'rb_300', label: '300 Pieces', count: 300, price: 2490, bulkPrice: null },
      { id: 'rb_400', label: '400 Pieces', count: 400, price: 3280, bulkPrice: null },
      { id: 'rb_500', label: '500 Pieces', count: 500, price: 4075, bulkPrice: 3750 },
      { id: 'rb_1000', label: '1,000 Pieces', count: 1000, price: 7800, bulkPrice: 7200 },
      { id: 'rb_2000', label: '2,000 Pieces', count: 2000, price: 15200, bulkPrice: 14000 },
      { id: 'rb_3000', label: '3,000 Pieces', count: 3000, price: 22500, bulkPrice: 20700 },
      { id: 'rb_4000', label: '4,000 Pieces', count: 4000, price: 29600, bulkPrice: 27200 },
      { id: 'rb_5000', label: '5,000 Pieces', count: 5000, price: 36250, bulkPrice: 33000 },
      { id: 'rb_6000', label: '6,000 Pieces', count: 6000, price: 43200, bulkPrice: 39000 },
    ],
    defaultVariantId: 'rb_500',
    perPiecePrice: 8.5,
    specs: {
      GRADE: 'Class A ISI',
      SIZE: '230×110×76 mm',
      'COMP. STRENGTH': '≥7.5 N/mm²',
      'WATER ABSORPTION': '≤20%',
    },
  },
  {
    id: 'bricks_grey_flash',
    name: 'Grey Flash Cement Bricks',
    brand: 'Regional Supplier',
    category: 'bricks',
    categoryLabel: 'Bricks',
    description: 'Cement-based grey flash bricks for load-bearing construction.',
    badge: null,
    status: 'IN STOCK',
    imageQuery: 'grey flash cement bricks construction',
    images: ['https://source.unsplash.com/featured/600x400/?grey+cement+blocks'],
    hasVariants: true,
    unit: 'Pieces',
    unitLabel: 'Pieces',
    variants: [
      { id: 'gb_100', label: '100 Pieces', count: 100, price: 700, bulkPrice: null },
      { id: 'gb_200', label: '200 Pieces', count: 200, price: 1380, bulkPrice: null },
      { id: 'gb_300', label: '300 Pieces', count: 300, price: 2040, bulkPrice: null },
      { id: 'gb_400', label: '400 Pieces', count: 400, price: 2680, bulkPrice: null },
      { id: 'gb_500', label: '500 Pieces', count: 500, price: 3300, bulkPrice: 3000 },
      { id: 'gb_1000', label: '1,000 Pieces', count: 1000, price: 6300, bulkPrice: 5800 },
      { id: 'gb_2000', label: '2,000 Pieces', count: 2000, price: 12200, bulkPrice: 11200 },
      { id: 'gb_3000', label: '3,000 Pieces', count: 3000, price: 18000, bulkPrice: 16500 },
      { id: 'gb_4000', label: '4,000 Pieces', count: 4000, price: 23600, bulkPrice: 21600 },
      { id: 'gb_5000', label: '5,000 Pieces', count: 5000, price: 29000, bulkPrice: 26500 },
      { id: 'gb_6000', label: '6,000 Pieces', count: 6000, price: 34200, bulkPrice: 31200 },
    ],
    defaultVariantId: 'gb_500',
    specs: {
      GRADE: 'Standard',
      SIZE: '230×110×76 mm',
      TYPE: 'Cement Block',
      USE: 'Load Bearing',
    },
  },
  {
    id: 'agg_jeera_rodi',
    name: 'Jeera Rodi',
    brand: 'Local',
    category: 'aggregates',
    categoryLabel: 'Aggregates',
    description: 'Fine aggregate (Jeera Rodi) for concrete and plastering work.',
    badge: null,
    status: 'IN STOCK',
    imageQuery: 'jeera rodi aggregate construction',
    images: ['https://source.unsplash.com/featured/600x400/?stone+aggregate'],
    hasVariants: true,
    unit: 'CFT',
    unitLabel: 'CFT',
    variants: [
      { id: 'jr_10', label: '10 CFT', quantity: 10, price: 700, bulkPrice: null },
      { id: 'jr_20', label: '20 CFT', quantity: 20, price: 1350, bulkPrice: null },
      { id: 'jr_30', label: '30 CFT', quantity: 30, price: 1980, bulkPrice: null },
      { id: 'jr_40', label: '40 CFT', quantity: 40, price: 2600, bulkPrice: null },
      { id: 'jr_50', label: '50 CFT', quantity: 50, price: 3200, bulkPrice: null },
      { id: 'jr_60', label: '60 CFT', quantity: 60, price: 3750, bulkPrice: null },
      { id: 'jr_70', label: '70 CFT', quantity: 70, price: 4250, bulkPrice: null },
      { id: 'jr_80', label: '80 CFT', quantity: 80, price: 4700, bulkPrice: null },
      { id: 'jr_90', label: '90 CFT', quantity: 90, price: 5100, bulkPrice: null },
    ],
    defaultVariantId: 'jr_10',
    specs: {
      TYPE: 'Fine Aggregate',
      SIZE: '6mm – 10mm',
      GRADE: 'Grade A',
      USE: 'Concrete / Plaster',
    },
  },
  {
    id: 'adh_fevicol_marine',
    name: 'Fevicol Marine',
    brand: 'Fevicol',
    category: 'adhesives',
    categoryLabel: 'Adhesives',
    description: 'Water-resistant marine adhesive for wood, laminate, and exterior bonding.',
    badge: null,
    status: 'IN STOCK',
    imageQuery: 'fevicol marine adhesive',
    images: ['https://source.unsplash.com/featured/600x400/?adhesive+glue+bottle'],
    hasVariants: true,
    unit: 'ml/L',
    variants: [
      { id: 'fm_250', label: '250 ml', displayUnit: '250 ml', price: 180, bulkPrice: null },
      { id: 'fm_500', label: '500 ml', displayUnit: '500 ml', price: 320, bulkPrice: null },
      { id: 'fm_1l', label: '1 L', displayUnit: '1 L', price: 580, bulkPrice: null },
      { id: 'fm_4l', label: '4 L', displayUnit: '4 L', price: 1950, bulkPrice: null },
    ],
    defaultVariantId: 'fm_250',
    specs: {
      TYPE: 'Synthetic Resin',
      'SETTING TIME': '15–30 mins',
      'TEMP RANGE': '-10°C to 60°C',
      APPLICATION: 'Interior / Exterior',
    },
  },
  {
    id: 'adh_fevicol_sh',
    name: 'Fevicol SH',
    brand: 'Fevicol',
    category: 'adhesives',
    categoryLabel: 'Adhesives',
    description: 'Synthetic resin adhesive for wood, furniture, and laminates.',
    badge: 'POPULAR',
    status: 'IN STOCK',
    imageQuery: 'fevicol sh adhesive',
    images: ['https://source.unsplash.com/featured/600x400/?wood+glue'],
    hasVariants: true,
    unit: 'ml/L',
    variants: [
      { id: 'fs_250', label: '250 ml', displayUnit: '250 ml', price: 150, bulkPrice: null },
      { id: 'fs_500', label: '500 ml', displayUnit: '500 ml', price: 275, bulkPrice: null },
      { id: 'fs_1l', label: '1 L', displayUnit: '1 L', price: 490, bulkPrice: null },
      { id: 'fs_4l', label: '4 L', displayUnit: '4 L', price: 1650, bulkPrice: null },
    ],
    defaultVariantId: 'fs_250',
    specs: {
      TYPE: 'PVA Resin',
      'SETTING TIME': '20–40 mins',
      'BOND STRENGTH': 'High',
      APPLICATION: 'Interior',
    },
  },
  {
    id: 'adh_fevicol_heatx',
    name: 'Fevicol HeatX',
    brand: 'Fevicol',
    category: 'adhesives',
    categoryLabel: 'Adhesives',
    description: 'Heat-resistant adhesive for high-temperature applications.',
    badge: null,
    status: 'IN STOCK',
    imageQuery: 'fevicol heatx adhesive',
    images: ['https://source.unsplash.com/featured/600x400/?adhesive+industrial'],
    hasVariants: true,
    unit: 'ml/L',
    variants: [
      { id: 'fh_250', label: '250 ml', displayUnit: '250 ml', price: 220, bulkPrice: null },
      { id: 'fh_500', label: '500 ml', displayUnit: '500 ml', price: 400, bulkPrice: null },
      { id: 'fh_1l', label: '1 L', displayUnit: '1 L', price: 720, bulkPrice: null },
      { id: 'fh_4l', label: '4 L', displayUnit: '4 L', price: 2400, bulkPrice: null },
    ],
    defaultVariantId: 'fh_250',
    specs: {
      TYPE: 'Heat Resistant Resin',
      'MAX TEMP': '200°C',
      'SETTING TIME': '10–20 mins',
      APPLICATION: 'High-Heat Surfaces',
    },
  },
  {
    id: 'adh_fevicol_speedx',
    name: 'Fevicol SpeedX',
    brand: 'Fevicol',
    category: 'adhesives',
    categoryLabel: 'Adhesives',
    description: 'Fast-setting contact adhesive for quick bonding.',
    badge: null,
    status: 'IN STOCK',
    imageQuery: 'fevicol speedx adhesive',
    images: ['https://source.unsplash.com/featured/600x400/?contact+adhesive'],
    hasVariants: true,
    unit: 'ml/L',
    variants: [
      { id: 'fsx_250', label: '250 ml', displayUnit: '250 ml', price: 195, bulkPrice: null },
      { id: 'fsx_500', label: '500 ml', displayUnit: '500 ml', price: 360, bulkPrice: null },
      { id: 'fsx_1l', label: '1 L', displayUnit: '1 L', price: 640, bulkPrice: null },
      { id: 'fsx_4l', label: '4 L', displayUnit: '4 L', price: 2100, bulkPrice: null },
    ],
    defaultVariantId: 'fsx_250',
    specs: {
      TYPE: 'Contact Adhesive',
      'SETTING TIME': '5–10 mins',
      'BOND STRENGTH': 'Very High',
      APPLICATION: 'Rubber / Leather / Wood',
    },
  },
  {
    id: 'adh_jivantor',
    name: 'Jivantor',
    brand: 'Jivantor',
    category: 'adhesives',
    categoryLabel: 'Adhesives',
    description: 'Heavy-duty construction adhesive for masonry and tiles.',
    badge: null,
    status: 'IN STOCK',
    imageQuery: 'jivantor adhesive',
    images: ['https://source.unsplash.com/featured/600x400/?construction+adhesive'],
    hasVariants: true,
    unit: 'ml/L',
    variants: [
      { id: 'jv_250', label: '250 ml', displayUnit: '250 ml', price: 160, bulkPrice: null },
      { id: 'jv_500', label: '500 ml', displayUnit: '500 ml', price: 290, bulkPrice: null },
      { id: 'jv_1l', label: '1 L', displayUnit: '1 L', price: 520, bulkPrice: null },
      { id: 'jv_4l', label: '4 L', displayUnit: '4 L', price: 1750, bulkPrice: null },
      { id: 'jv_10l', label: '10 L', displayUnit: '10 L', price: 3900, bulkPrice: 3600 },
      { id: 'jv_20l', label: '20 L', displayUnit: '20 L', price: 7400, bulkPrice: 6800 },
    ],
    defaultVariantId: 'jv_250',
    specs: {
      TYPE: 'Polymer Modified',
      'SETTING TIME': '30–60 mins',
      COVERAGE: '8–10 sq ft/L',
      APPLICATION: 'Tiles / Masonry',
    },
  },
  {
    id: 'wall_jk_putty',
    name: 'JK Wall Putty',
    brand: 'JK',
    category: 'wall_repair',
    categoryLabel: 'Wall Repair',
    description: 'White cement-based wall putty for smooth wall finish.',
    badge: null,
    status: 'IN STOCK',
    imageQuery: 'jk wall putty',
    images: ['https://source.unsplash.com/featured/600x400/?wall+putty+white'],
    hasVariants: true,
    unit: 'Bucket',
    variants: [
      { id: 'jkp_5', label: '5 Kg Bucket', displayUnit: 'Bucket', weight: 5, price: 260, bulkPrice: null },
      { id: 'jkp_10', label: '10 Kg Bucket', displayUnit: 'Bucket', weight: 10, price: 490, bulkPrice: 460 },
      { id: 'jkp_20', label: '20 Kg Bucket', displayUnit: 'Bucket', weight: 20, price: 940, bulkPrice: 880 },
    ],
    defaultVariantId: 'jkp_5',
    specs: {
      TYPE: 'White Cement Based',
      COVERAGE: '12–14 sq ft/kg',
      'DRYING TIME': '4–6 hrs',
      APPLICATION: 'Interior / Exterior Walls',
    },
  },
  {
    id: 'wall_birla_putty',
    name: 'Birla Putty',
    brand: 'Birla',
    category: 'wall_repair',
    categoryLabel: 'Wall Repair',
    description: 'Premium acrylic putty for smooth, crack-free wall surfaces.',
    badge: 'POPULAR',
    status: 'IN STOCK',
    imageQuery: 'birla wall putty',
    images: ['https://source.unsplash.com/featured/600x400/?wall+plaster'],
    hasVariants: true,
    unit: 'Bucket',
    variants: [
      { id: 'bp_5', label: '5 Kg Bucket', displayUnit: 'Bucket', weight: 5, price: 300, bulkPrice: null },
      { id: 'bp_10', label: '10 Kg Bucket', displayUnit: 'Bucket', weight: 10, price: 560, bulkPrice: 520 },
      { id: 'bp_20', label: '20 Kg Bucket', displayUnit: 'Bucket', weight: 20, price: 1050, bulkPrice: 980 },
    ],
    defaultVariantId: 'bp_5',
    specs: {
      TYPE: 'Acrylic White Putty',
      COVERAGE: '14–16 sq ft/kg',
      'DRYING TIME': '3–5 hrs',
      APPLICATION: 'Interior Walls',
    },
  },
  {
    id: 'wall_sakarni_pop',
    name: 'Sakarni POP',
    brand: 'Sakarni',
    category: 'wall_repair',
    categoryLabel: 'Wall Repair',
    description: 'Plaster of Paris for false ceilings, decorative work, and wall finishing.',
    badge: null,
    status: 'IN STOCK',
    imageQuery: 'sakarni pop',
    images: ['https://source.unsplash.com/featured/600x400/?plaster+ceiling'],
    hasVariants: true,
    unit: 'Bag',
    variants: [
      { id: 'pop_5', label: '5 Kg Bag', displayUnit: 'Bag', weight: 5, price: 90, bulkPrice: null },
      { id: 'pop_10', label: '10 Kg Bag', displayUnit: 'Bag', weight: 10, price: 170, bulkPrice: null },
      { id: 'pop_20', label: '20 Kg Bag', displayUnit: 'Bag', weight: 20, price: 320, bulkPrice: 295 },
      { id: 'pop_50', label: '50 Kg Bag', displayUnit: 'Bag', weight: 50, price: 750, bulkPrice: 680 },
    ],
    defaultVariantId: 'pop_10',
    specs: {
      TYPE: 'Plaster of Paris',
      'SETTING TIME': '20–30 mins',
      COVERAGE: '1 kg = 1 sq ft (6mm)',
      APPLICATION: 'False Ceiling / Wall Décor',
    },
  },
  {
    id: 'wall_white_cement',
    name: 'White Cement',
    brand: 'Local',
    category: 'wall_repair',
    categoryLabel: 'Wall Repair',
    description: 'White cement for tile grouting, coping, and decorative finishes.',
    badge: null,
    status: 'IN STOCK',
    imageQuery: 'white cement construction',
    images: ['https://source.unsplash.com/featured/600x400/?white+cement'],
    hasVariants: true,
    unit: 'Bag',
    variants: [
      { id: 'wc_1', label: '1 Kg Bag', displayUnit: 'Bag', weight: 1, price: 30, bulkPrice: null },
      { id: 'wc_5', label: '5 Kg Bag', displayUnit: 'Bag', weight: 5, price: 140, bulkPrice: null },
      { id: 'wc_10', label: '10 Kg Bag', displayUnit: 'Bag', weight: 10, price: 265, bulkPrice: 245 },
      { id: 'wc_20', label: '20 Kg Bag', displayUnit: 'Bag', weight: 20, price: 500, bulkPrice: 460 },
    ],
    defaultVariantId: 'wc_5',
    specs: {
      TYPE: 'White Portland Cement',
      GRADE: '33 Grade',
      'SETTING TIME': '45–60 mins',
      USE: 'Grouting / Decorative',
    },
  },
  {
    id: 'putty_ap_acrylic',
    name: 'Acrylic Putty',
    brand: 'Asian Paints',
    category: 'putty',
    categoryLabel: 'Putty',
    description: 'Asian Paints acrylic wall putty for smooth interior wall finish.',
    badge: 'POPULAR',
    status: 'IN STOCK',
    imageQuery: 'asian paints acrylic putty',
    images: ['https://source.unsplash.com/featured/600x400/?paint+putty+wall'],
    hasVariants: true,
    unit: 'Bucket',
    variants: [
      { id: 'ap_10', label: '10 L Bucket', displayUnit: 'Bucket', volume: 10, price: 1800, bulkPrice: 1650 },
      { id: 'ap_20', label: '20 L Bucket', displayUnit: 'Bucket', volume: 20, price: 3400, bulkPrice: 3100 },
    ],
    defaultVariantId: 'ap_10',
    specs: {
      TYPE: 'Acrylic Emulsion Based',
      COVERAGE: '40–50 sq ft/L',
      'DRYING TIME': '2–4 hrs',
      APPLICATION: 'Interior Smooth Finish',
    },
  },
];

export function getCatalogProductById(id: string): CatalogProduct | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id);
}
