import type { AppLanguage } from '@store/languageStore';

export const strings = {
  en: {
    // Complete Profile
    completeProfileTitle: 'Complete Your Profile',
    completeProfileSubtitle:
      'Tell us about your business to get started with verified procurement.',
    companyName: 'Company Name',
    companyNamePlaceholder: 'Enter your company name',
    gstNumber: 'GST Number (optional)',
    gstPlaceholder: '22AAAAA0000A1Z5',
    chooseLanguage: 'Choose Your Preferred Language',
    languageSubtitle: "Continue in the language you're most comfortable with.",
    hindiLink: 'अपनी पसंदीदा भाषा चुनें',
    recommendedRegion: 'Recommended based on your region',
    english: 'English',
    continueInEnglish: 'Continue in English',
    hindi: 'हिंदी',
    continueInHindi: 'हिंदी में जारी रखें',
    isoSecurity: 'ISO 27001 CERTIFIED ENTERPRISE SECURITY',
    continueBtn: 'Continue',

    // Delivery Location
    deliveryLocation: 'Delivery Location',
    searchSiteAddress: 'Search for Site Address',
    preciseGpsPinning: 'Precise GPS Pinning',
    savedDeliverySites: 'Saved Delivery Sites',
    manageProjects: 'Manage your active construction projects',
    addNewSite: 'Add New Site',
    registerDeliveryPoint: 'Register a new delivery point',
    industrialPrecision: 'Industrial Precision',
    industrialPrecisionDesc:
      'Our system uses high-accuracy geo-fencing to ensure materials are dropped exactly where your crew needs them.',
    siteLogisticsSupport: 'Site Logistics Support',
    siteLogisticsSupportDesc:
      'Need specific gate entry instructions? Add them to your site profile and our drivers will follow every protocol.',
    allowFetchLocation: 'Allow Fetch Location',
    addressLine1: 'Address Line 1',
    city: 'City',
    pincode: 'Pincode',
    siteName: 'Site Name',
    fullAddress: 'Full Address',
    gateInstructions: 'Gate Instructions (optional)',
    saveSite: 'Save Site',
    edit: 'Edit',
    delete: 'Delete',

    // Home
    goodMorning: 'Good Morning, Rajesh',
    readyToScale: 'Ready to scale the skyline today?',
    searchMaterials: 'Search Materials',
    twoHourDelivery: '⚡ 2-Hour Delivery',
    heroTitle: 'Everything Your Site Needs — Delivered Fast',
    shopNow: 'Shop Now',
    bulkInquiry: 'Bulk Inquiry',
    platinumTier: 'PLATINUM TIER',
    loyaltyProgress: 'Loyalty Progress',
    platinumNext: 'Platinum Next',
    loyaltyPoints: '10 / 600 PTS',
    earnPoints: 'Earn 150 more points for free logistics on next order.',
    materialCategories: 'Material Categories',
    viewCatalog: 'View Cat.',
    cement: 'Cement',
    steel: 'Steel',
    stoneChips: 'Stone Chips',
    sand: 'Sand',
    bricks: 'Bricks',
    criticalShortage: 'Critical project shortage?',
    emergencySubtitle:
      'Get essential materials delivered to your site in under 90 minutes. 24/7 Logistics at your command.',
    emergencyOrder: '⚡ Emergency Order',
    enRoute: 'EN ROUTE',
    orderId: 'Order #CIQ-8829',
    deliveryIn: 'Delivery in 24 mins',
    deliveryItems: '50 Bags UltraTech Concrete Mix - Site A',
    callDriver: 'Call Driver',
    vehicleNumber: 'KA-01-HL-4290',
    smartReorder: 'Smart Reorder',
    tmtBars: 'TMT 12mm Bars',
    tmtOrdered: 'Last ordered 4d ago',
    pvcPipes: 'PVC Pipe Set (3")',
    pvcOrdered: 'Last ordered 2w ago',
    proStatus: 'PRO STATUS',
    points: '12,450 pts',
    progressToPlatinum: 'Progress to Platinum',
    redeemRewards: 'Redeem Rewards',

    // Catalog
    precisionProcurement: 'Precision Procurement',
    precisionProcurementDesc:
      'Streamline your construction site inventory with our curated selection of high-grade industrial materials and logistics-ready supplies.',
    bulkProcurementTitle: 'Bulk Procurement Discounts',
    bulkProcurementDesc:
      'Unlock up to 15% off on mixed material container loads. Optimize your site logistics with unified delivery schedules.',
    inquireNow: 'Inquire Now',
    priorityExpress: 'Priority Express',
    priorityExpressDesc:
      'Guaranteed same-day site delivery for all core inventory items.',
    searchProducts: 'Search cement, steel, bricks...',

    // Tabs
    tabHome: 'Home',
    tabCatalog: 'Catalog',
    tabOrders: 'Orders',
    tabAccount: 'Account',
    catalogComingSoon: 'Catalog — Coming Soon',
    ordersComingSoon: 'Orders — Coming Soon',
    accountComingSoon: 'Account — Coming Soon',

    // Drawer
    drawerHome: 'Home',
    drawerCatalog: 'Product Catalog',
    drawerOrders: 'My Orders',
    drawerTrackDeliveries: 'Track Deliveries',
    drawerSavedSites: 'Saved Sites',
    drawerGstInvoices: 'GST Invoices',
    drawerLoyalty: 'Loyalty & Rewards',
    drawerNotifications: 'Notifications',
    drawerProcurementTools: 'PROCUREMENT TOOLS',
    drawerEmergencyOrders: 'Emergency Orders',
    drawerBulkProcurement: 'Bulk Procurement',
    drawerOrderHistory: 'Order History',
    drawerSupport: 'SUPPORT',
    drawerHelpCenter: 'Help Center',
    drawerWhatsAppSupport: 'WhatsApp Support',
    drawerRaiseTicket: 'Raise Ticket',
    drawerPreferences: 'PREFERENCES',
    drawerLanguage: 'Language',
    drawerPrivacy: 'Privacy & Security',
    drawerTerms: 'Terms & Conditions',
    drawerLogout: 'Logout',
    drawerVersion: 'BuildQuick India v2.4.0',
    drawerLogoutTitle: 'Logout',
    drawerLogoutMessage: 'Are you sure you want to logout?',
    drawerLogoutConfirm: 'Logout',
    drawerLogoutCancel: 'Cancel',

    // Account
    accountEditProfile: 'Edit Profile',
    accountBusinessDetails: 'Business Details',
    accountLegalEntity: 'Legal Entity',
    accountEstablishmentDate: 'Establishment Date',
    accountRegisteredAddress: 'Registered Address',
    accountGstCompliance: 'GST Compliance',
    accountComplianceScore: 'Compliance Score',
    accountLanguage: 'Language / भाषा',
    accountUseEnglish: 'Use app in English',
    accountUseHindi: 'ऐप हिंदी में उपयोग करें',
    accountLanguageNote:
      'Orders, invoices, notifications and voice search will adapt to your selected language.',
    accountPaymentMethods: 'Payment Methods',
    accountLogoutTitle: 'Logout?',
    accountLogoutMessage: 'Are you sure you want to logout?',
    accountSaveChanges: 'Save All Changes',
    accountCancelChanges: 'Cancel Changes',
    accountPersonalDetails: 'Personal Details',
    accountBusinessProfile: 'Business Profile',
    accountActiveSites: 'Active Project Sites',
    accountAddNewSite: '+ Add New Site',
    accountDeliverySites: 'Delivery Sites',
    accountAddProjectSite: 'Add New Project Site',
    accountBusinessVerification: 'Business Verification',
    accountGstVerified: 'GST Verified',
    accountEntityInfo: 'Entity Information',
    accountGstCertificate: 'GST Certificate',
    accountDownloadPdf: 'Download PDF',
    accountInvoices: 'Invoices',
    accountSearchInvoices: 'Search Invoice ID, Site, or Vendor',
    accountConnectErp: 'Connect ERP',
    accountComingSoonErp: 'Coming Soon',
    accountProfileSaved: 'Profile updated successfully',
  },
  hi: {
    completeProfileTitle: 'अपनी प्रोफ़ाइल पूरी करें',
    completeProfileSubtitle:
      'सत्यापित खरीदारी शुरू करने के लिए अपने व्यवसाय के बारे में बताएं।',
    companyName: 'कंपनी का नाम',
    companyNamePlaceholder: 'अपनी कंपनी का नाम दर्ज करें',
    gstNumber: 'जीएसटी नंबर (वैकल्पिक)',
    gstPlaceholder: '22AAAAA0000A1Z5',
    chooseLanguage: 'अपनी पसंदीदा भाषा चुनें',
    languageSubtitle: 'उस भाषा में जारी रखें जिसमें आप सबसे सहज हैं।',
    hindiLink: 'अपनी पसंदीदा भाषा चुनें',
    recommendedRegion: 'आपके क्षेत्र के आधार पर अनुशंसित',
    english: 'English',
    continueInEnglish: 'Continue in English',
    hindi: 'हिंदी',
    continueInHindi: 'हिंदी में जारी रखें',
    isoSecurity: 'ISO 27001 प्रमाणित एंटरप्राइज़ सुरक्षा',
    continueBtn: 'जारी रखें',

    deliveryLocation: 'डिलीवरी स्थान',
    searchSiteAddress: 'साइट का पता खोजें',
    preciseGpsPinning: 'सटीक GPS पिनिंग',
    savedDeliverySites: 'सहेजे गए डिलीवरी साइट',
    manageProjects: 'अपनी सक्रिय निर्माण परियोजनाओं का प्रबंधन करें',
    addNewSite: 'नई साइट जोड़ें',
    registerDeliveryPoint: 'एक नया डिलीवरी पॉइंट पंजीकृत करें',
    industrialPrecision: 'औद्योगिक सटीकता',
    industrialPrecisionDesc:
      'हमारी प्रणाली उच्च-सटीकता जियो-फेंसिंग का उपयोग करती है ताकि सामग्री ठीक वहीं पहुंचे जहां आपकी टीम को जरूरत है।',
    siteLogisticsSupport: 'साइट लॉजिस्टिक्स सहायता',
    siteLogisticsSupportDesc:
      'विशिष्ट गेट प्रवेश निर्देश चाहिए? अपनी साइट प्रोफ़ाइल में जोड़ें और हमारे ड्राइवर हर प्रोटोकॉल का पालन करेंगे।',
    allowFetchLocation: 'स्थान अनुमति दें',
    addressLine1: 'पता पंक्ति 1',
    city: 'शहर',
    pincode: 'पिनकोड',
    siteName: 'साइट का नाम',
    fullAddress: 'पूरा पता',
    gateInstructions: 'गेट निर्देश (वैकल्पिक)',
    saveSite: 'साइट सहेजें',
    edit: 'संपादित करें',
    delete: 'हटाएं',

    goodMorning: 'सुप्रभात, राजेश',
    readyToScale: 'आज आकाश को छूने के लिए तैयार हैं?',
    searchMaterials: 'सामग्री खोजें',
    twoHourDelivery: '⚡ 2-घंटे डिलीवरी',
    heroTitle: 'आपकी साइट की हर जरूरत — तेजी से डिलीवर',
    shopNow: 'अभी खरीदें',
    bulkInquiry: 'थोक पूछताछ',
    platinumTier: 'प्लैटिनम टियर',
    loyaltyProgress: 'लॉयल्टी प्रगति',
    platinumNext: 'प्लैटिनम अगला',
    loyaltyPoints: '10 / 600 अंक',
    earnPoints: 'अगले ऑर्डर पर मुफ्त लॉजिस्टिक्स के लिए 150 और अंक कमाएं।',
    materialCategories: 'सामग्री श्रेणियां',
    viewCatalog: 'कैटलॉग देखें',
    cement: 'सीमेंट',
    steel: 'स्टील',
    stoneChips: 'पत्थर चिप्स',
    sand: 'रेत',
    bricks: 'ईंटें',
    criticalShortage: 'गंभीर परियोजना की कमी?',
    emergencySubtitle:
      '90 मिनट के भीतर आवश्यक सामग्री अपनी साइट पर पाएं। 24/7 लॉजिस्टिक्स आपके आदेश पर।',
    emergencyOrder: '⚡ आपातकालीन ऑर्डर',
    enRoute: 'रास्ते में',
    orderId: 'ऑर्डर #CIQ-8829',
    deliveryIn: '24 मिनट में डिलीवरी',
    deliveryItems: '50 बैग UltraTech कंक्रीट मिक्स - साइट A',
    callDriver: 'ड्राइवर को कॉल करें',
    vehicleNumber: 'KA-01-HL-4290',
    smartReorder: 'स्मार्ट पुनः ऑर्डर',
    tmtBars: 'TMT 12mm बार',
    tmtOrdered: '4 दिन पहले ऑर्डर किया',
    pvcPipes: 'PVC पाइप सेट (3")',
    pvcOrdered: '2 सप्ताह पहले ऑर्डर किया',
    proStatus: 'प्रो स्थिति',
    points: '12,450 अंक',
    progressToPlatinum: 'प्लैटिनम की ओर प्रगति',
    redeemRewards: 'पुरस्कार रिडीम करें',

    precisionProcurement: 'सटीक खरीदारी',
    precisionProcurementDesc:
      'उच्च-ग्रेड औद्योगिक सामग्री और लॉजिस्टिक्स-तैयार आपूर्ति के हमारे चयनित संग्रह के साथ अपनी निर्माण साइट इन्वेंटरी को सुव्यवस्थित करें।',
    bulkProcurementTitle: 'थोक खरीदारी छूट',
    bulkProcurementDesc:
      'मिश्रित सामग्री कंटेनर लोड पर 15% तक की छूट पाएं। एकीकृत डिलीवरी अनुसूची के साथ अपनी साइट लॉजिस्टिक्स को अनुकूलित करें।',
    inquireNow: 'अभी पूछताछ करें',
    priorityExpress: 'प्राथमिकता एक्सप्रेस',
    priorityExpressDesc:
      'सभी मुख्य इन्वेंटरी वस्तुओं के लिए गारंटीशुदा उसी दिन साइट डिलीवरी।',
    searchProducts: 'सीमेंट, स्टील, ईंटें खोजें...',

    tabHome: 'होम',
    tabCatalog: 'कैटलॉग',
    tabOrders: 'ऑर्डर',
    tabAccount: 'खाता',
    catalogComingSoon: 'कैटलॉग — जल्द आ रहा है',
    ordersComingSoon: 'ऑर्डर — जल्द आ रहा है',
    accountComingSoon: 'खाता — जल्द आ रहा है',

    drawerHome: 'होम',
    drawerCatalog: 'उत्पाद कैटलॉग',
    drawerOrders: 'मेरे ऑर्डर',
    drawerTrackDeliveries: 'डिलीवरी ट्रैक करें',
    drawerSavedSites: 'सहेजी गई साइटें',
    drawerGstInvoices: 'जीएसटी चालान',
    drawerLoyalty: 'लॉयल्टी और पुरस्कार',
    drawerNotifications: 'सूचनाएं',
    drawerProcurementTools: 'खरीदारी उपकरण',
    drawerEmergencyOrders: 'आपातकालीन ऑर्डर',
    drawerBulkProcurement: 'थोक खरीदारी',
    drawerOrderHistory: 'ऑर्डर इतिहास',
    drawerSupport: 'सहायता',
    drawerHelpCenter: 'सहायता केंद्र',
    drawerWhatsAppSupport: 'व्हाट्सएप सहायता',
    drawerRaiseTicket: 'टिकट बनाएं',
    drawerPreferences: 'प्राथमिकताएं',
    drawerLanguage: 'भाषा',
    drawerPrivacy: 'गोपनीयता और सुरक्षा',
    drawerTerms: 'नियम और शर्तें',
    drawerLogout: 'लॉगआउट',
    drawerVersion: 'BuildQuick India v2.4.0',
    drawerLogoutTitle: 'लॉगआउट',
    drawerLogoutMessage: 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
    drawerLogoutConfirm: 'लॉगआउट',
    drawerLogoutCancel: 'रद्द करें',

    // Account
    accountEditProfile: 'प्रोफ़ाइल संपादित करें',
    accountBusinessDetails: 'व्यवसाय विवरण',
    accountLegalEntity: 'कानूनी इकाई',
    accountEstablishmentDate: 'स्थापना तिथि',
    accountRegisteredAddress: 'पंजीकृत पता',
    accountGstCompliance: 'जीएसटी अनुपालन',
    accountComplianceScore: 'अनुपालन स्कोर',
    accountLanguage: 'Language / भाषा',
    accountUseEnglish: 'Use app in English',
    accountUseHindi: 'ऐप हिंदी में उपयोग करें',
    accountLanguageNote:
      'ऑर्डर, चालान, सूचनाएं और वॉयस सर्च आपकी चुनी भाषा के अनुसार बदलेंगे।',
    accountPaymentMethods: 'भुगतान विधियां',
    accountLogoutTitle: 'लॉगआउट?',
    accountLogoutMessage: 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
    accountSaveChanges: 'सभी परिवर्तन सहेजें',
    accountCancelChanges: 'परिवर्तन रद्द करें',
    accountPersonalDetails: 'व्यक्तिगत विवरण',
    accountBusinessProfile: 'व्यवसाय प्रोफ़ाइल',
    accountActiveSites: 'सक्रिय परियोजना साइटें',
    accountAddNewSite: '+ नई साइट जोड़ें',
    accountDeliverySites: 'डिलीवरी साइटें',
    accountAddProjectSite: 'नई परियोजना साइट जोड़ें',
    accountBusinessVerification: 'व्यवसाय सत्यापन',
    accountGstVerified: 'जीएसटी सत्यापित',
    accountEntityInfo: 'इकाई जानकारी',
    accountGstCertificate: 'जीएसटी प्रमाणपत्र',
    accountDownloadPdf: 'PDF डाउनलोड करें',
    accountInvoices: 'चालान',
    accountSearchInvoices: 'चालान ID, साइट या विक्रेता खोजें',
    accountConnectErp: 'ERP कनेक्ट करें',
    accountComingSoonErp: 'जल्द आ रहा है',
    accountProfileSaved: 'प्रोफ़ाइल सफलतापूर्वक अपडेट हुई',
  },
} as const satisfies Record<AppLanguage, Record<string, string>>;

export type StringKey = keyof (typeof strings)['en'];
