export const strings = {
  en: {
    tabHome: 'Home',
    tabCatalog: 'Catalog',
    tabOrders: 'Orders',
    tabAccount: 'Account',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    loading: 'Loading...',
    viewAll: 'View All',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    close: 'Close',
    done: 'Done',
    next: 'Next',
    submit: 'Submit',
    retry: 'Retry',
    or: 'or',
    free: 'FREE',
    paid: 'PAID',
    pending: 'PENDING',
    verified: 'VERIFIED',
    active: 'ACTIVE',
    optional: 'optional',
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    homeSubtitle: 'Ready to scale the skyline today?',
    searchMaterials: 'Search Materials',
    searchPlaceholder: 'Search premium construction materials...',
    twoHourDelivery: '2-Hour Delivery',
    heroBannerTitle: 'Everything Your Site Needs — Delivered Fast',
    shopNow: 'Shop Now',
    bulkInquiry: 'Bulk Inquiry',
    platinumTier: 'PLATINUM TIER',
    loyaltyProgress: 'Loyalty Progress',
    platinumNext: 'Platinum Next',
    earnPoints: 'Earn 150 more points for free logistics on next order.',
    materialCategories: 'Material Categories',
    viewCat: 'View All',
    criticalShortage: 'Critical project shortage?',
    criticalSubtitle: 'Get essential materials delivered to your site in under 90 minutes. 24/7 Logistics at your command.',
    emergencyOrder: 'Emergency Order',
    emergencyDeliveryTitle: 'Emergency Delivery',
    emergencyDeliverySubtitle: 'Site running short? Get essential materials to your site fast — 24/7 logistics.',
    emergencyEta: '30–90 Minutes',
    orderNow: 'Order Now',
    membershipBadge: 'MEMBERSHIP',
    membershipTitle: 'Bajriwala Membership',
    membershipSubtitle: 'Unlock premium savings and perks for your sites.',
    membershipPerYear: 'year',
    membershipExtraDiscount: 'Extra Discount',
    membershipFreeDelivery: 'Free Delivery',
    membershipBulkDiscounts: 'Bulk Discounts',
    membershipInternationalTrips: 'International Trips',
    membershipLuckyDraw: 'Lucky Draw',
    membershipLoyaltyPoints: 'Loyalty Points',
    joinNow: 'Join Now',
    membershipJoinMock: 'Membership signup coming soon. You will be notified!',
    bulkProcurementSection: 'Bulk Procurement',
    bulkProcurementCardTitle: 'Bulk Procurement Benefits',
    bulkProcurementCardSubtitle: 'Unlock exclusive benefits for large construction orders.',
    unlock: 'Unlock',
    bulkUnlockDiscount: 'Unlock Discount up to 15%',
    bulkUnlockTrips: 'International Trips',
    bulkUnlockLuckyDraw: 'Lucky Draw',
    bulkUnlockLoyalty: 'Loyalty Points',
    unlockBenefits: 'Unlock Benefits',
    knowMore: 'Know More',
    customerTestimonials: 'Customer Testimonials',
    customerTestimonialsSubtitle:
      'Trusted by Contractors, Builders and Home Owners across India.',
    loadingTestimonial: 'Loading testimonial...',
    unableToPlayVideo: 'Unable to play video',
    skipForNow: 'Skip',
    skipGst: 'Skip →',
    skipProfile: 'Skip',
    addGstNumber: '+ Add GST Number',
    gstSkippedLabel: 'GST skipped for now',
    gstOptionalHint:
      'If you have a GST certificate, add it to unlock Business pricing and GST invoices. You can skip this now and add it later in your profile.',
    hardware: 'Hardware',
    cantFindProduct: "Can't find your product?",
    speakToExpert: 'Speak to our Material Expert',
    talkToExpert: 'Talk to Expert',
    expertSheetSubtitle: 'Tell us what you need — our expert will call you back shortly.',
    yourName: 'Your Name',
    namePlaceholder: 'Enter your name',
    whatDoYouNeed: 'What do you need?',
    needPlaceholder: 'e.g. 200 bags OPC 53, Fe500 TMT 12mm...',
    requestCallback: 'Request Callback',
    expertRequestSent: 'Request received',
    expertRequestBody: 'Our material expert will contact you shortly. (Mock)',
    bulkPriceBadge: 'Bulk Price',
    bulkPricingTitle: 'Bulk Pricing',
    deliveryEtaLabel: 'Delivery',
    onlyXLeft: 'Only {count} left',
    add: 'ADD',
    added: 'ADDED',
    addedToCartBtn: 'Added ✓',
    updateCart: 'Update Cart',
    wallet: 'Wallet',
    refundHistory: 'Refund History',
    walletBalanceHint: 'Use wallet balance at checkout when available.',
    walletComingSoonBody: 'Top-ups, cashback, and transfers are coming soon.',
    completed: 'Completed',
    failed: 'Failed',
    deliveryCharge: 'Delivery',
    loadingCharges: 'Loading Charges',
    unloadingCharges: 'Unloading Charges',
    walletDeduction: 'Wallet',
    bikeDelivery: 'Bike Delivery',
    bikeDeliveryFree: 'FREE',
    paymentWallet: 'Wallet',
    paymentUpi: 'UPI',
    walletDisabledHint: 'Wallet unavailable (balance ₹0)',
    smartReorder: 'Smart Reorder',
    lastOrders: 'Last Orders',
    lastOrdersSubtitle: "Items you've ordered before",
    lastOrdered: 'Last ordered',
    viewProduct: 'View',
    recommendedProducts: 'Recommended Products',
    recommendedForYou: 'Recommended For You',
    recommendedSubtitle: 'Products based on your browsing and purchases',
    recommendedBecause: 'Recommended because',
    recommendedPreviouslyOrdered: 'Previously Ordered',
    recommendedPopularNearYou: 'Popular Near You',
    recommendedFrequentlyBought: 'Frequently Bought',
    noLastOrdersPrompt: 'No orders yet',
    noLastOrdersSubtitle: 'Your last ordered items will appear here',
    shop: 'Shop',
    callDriver: 'Call Driver',
    redeemRewards: 'Redeem Rewards',
    progressToPlatinum: 'Progress to Platinum',
    deliveryIn: 'Delivery in',
    enRoute: 'EN ROUTE',
    proStatus: 'PRO STATUS',
    cement: 'Cement',
    steel: 'Steel',
    sand: 'Sand',
    bricksAndMasonry: 'Bricks & Masonry',
    greyFillSand: 'Grey Fill Sand',
    stoneChip: 'Stone Chip',
    aggregates: 'Aggregates',
    adhesives: 'Adhesives',
    wallRepair: 'Wall Repair',
    waterproofing: 'Waterproofing',
    quickRepair: 'Quick Repair',
    putty: 'Putty',
    productsCount: '{count} Products',
    loginMobileInvalid: 'Please enter a valid 10-digit mobile number.',
    plumbing: 'Plumbing',
    electrical: 'Electrical',
    catalogTitle: 'Precision Procurement',
    catalogSubtitle: 'Streamline your construction site inventory with our curated selection of high-grade industrial materials and logistics-ready supplies.',
    bulkProcurementTitle: 'Bulk Procurement Discounts',
    bulkProcurementSubtitle: 'Unlock up to 15% off on mixed material container loads. Optimize your site logistics with unified delivery schedules.',
    inquireNow: 'Inquire Now',
    priorityExpress: 'Priority Express',
    priorityExpressSubtitle: 'Guaranteed same-day site delivery for all core inventory items.',
    searchCatalog: 'Search cement, steel, bricks...',
    readyForDispatch: 'READY FOR DISPATCH',
    inStock: 'IN STOCK',
    limitedStock: 'LIMITED STOCK',
    outOfStock: 'OUT OF STOCK',
    trending: 'TRENDING',
    popular: 'POPULAR',
    new: 'NEW',
    bulkSavings: 'BULK SAVINGS',
    getReady: 'GET READY',
    retailPrice: 'Retail Price',
    bulkPrice: 'Bulk Price',
    minOrder: 'Minimum',
    grade: 'Grade',
    perBag: 'per bag',
    perTon: 'per ton',
    perPiece: 'per piece',
    addToCart: 'Add to Cart',
    viewOrder: 'View Order',
    details: 'Details',
    productDetail: 'Product Detail',
    technicalSpecs: 'Technical Specifications',
    financials: 'FINANCIALS',
    gstInvoiceReady: 'GST Invoice Ready',
    shipping: 'SHIPPING',
    flatbedLogistics: 'Flatbed Logistics',
    gradeLabel: 'GRADE',
    settingTime: 'SETTING TIME',
    strength: 'STRENGTH',
    compression: 'COMPRESSION',
    superiorDurability: 'Superior Durability',
    projectSiteSelection: 'Project Site Selection',
    totalSubtotal: 'Total Subtotal',
    pricingSummary: 'PRICING SUMMARY',
    baseRate: 'Base Rate',
    subtotal: 'Subtotal',
    logistics: 'Logistics (Express)',
    gst18: 'GST (18%)',
    estimatedTotal: 'ESTIMATED TOTAL',
    quickQuote: 'QUICK QUOTE',
    pricesLocked: 'Prices are dynamic and locked for 15 minutes. Final weight bridge certificate provided at site.',
    deliveryLogistics: 'Delivery & Logistics',
    availableNow: 'Available Now',
    deliveryIn24: 'Delivery in 2–4 Hours',
    nearestWarehouse: 'Nearest warehouse',
    priority: 'Priority',
    standard: 'Standard',
    scheduled: 'Scheduled',
    chooseSlot: 'Choose slot',
    siteReady: 'Site-ready',
    logisticsBreakdown: 'LOGISTICS BREAKDOWN',
    heavyLoad: 'Heavy Load',
    distance: 'Distance',
    unloadingHelp: 'Unloading Help',
    fastestDelivery: 'Fastest delivery to',
    materialsAvailable: 'Materials available at',
    warehouse: 'WAREHOUSE',
    vehicle: 'VEHICLE',
    frequentlyBought: 'Frequently Bought Together',
    addBundle: 'Add Bundle',
    yourCart: 'Your Cart',
    activeItems: 'Active Items',
    saveForLater: 'Save for later',
    buildProPoints: 'BajriPro Points',
    balance: 'Balance',
    usePointsToSave: 'Use 2,500 points to save ₹500',
    orderSummary: 'ORDER SUMMARY',
    itemsTotal: 'Items Total',
    deliveryCharges: 'Delivery Charges',
    loyaltyDiscount: 'Loyalty Discount',
    grandTotal: 'GRAND TOTAL',
    totalPrice: 'Total Price',
    proceedCheckout: 'Proceed to Checkout',
    secureCheckout: 'Secure checkout',
    emptyCart: 'Your cart is empty',
    emptyCartSubtitle: 'Add materials to get started',
    browseCatalog: 'Browse Catalog',
    checkout: 'Checkout',
    deliveryDestination: 'DELIVERY DESTINATION',
    change: 'Change',
    scheduledDelivery: 'Scheduled Delivery',
    gstNumber: 'GST Number',
    billDetails: 'Bill Details',
    gstInvoiceCardTitle: 'GST Invoice',
    gstInvoiceCardSubtitle: 'Add GST details to receive GST Invoice for Business Purchases',
    gstInvoiceApplied: 'GST Invoice Applied',
    gstInvoiceAppliedNote: 'Invoice will be generated using your GSTIN.',
    gstInvoiceEnabled: 'GST Invoice Enabled',
    businessInvoiceEnabled: 'Business Invoice Enabled',
    gstSuccessBannerTitle: 'Business GST Verified',
    gstSuccessBannerSubtitle: 'Business pricing unlocked',
    gstBusinessInvoiceEnabled: 'GST Business Invoice Enabled',
    gstBusinessInvoiceEligible: 'Eligible for Business Tax Invoice',
    gstBusinessDiscountNote: 'Standard B2B pricing · Input tax credit eligible',
    totalBeforeGstDiscount: 'Total before GST discount',
    gstBusinessDiscountApplied: 'GST Business Discount Applied',
    withVerifiedGstPricing: 'with verified GST pricing',
    businessBenefits: 'Business Benefits',
    gstBenefitInvoice: 'GST Invoice',
    gstBenefitAccounting: 'Faster Accounting',
    gstBenefitHistory: 'Business Purchase History',
    gstBenefitItc: 'Input Tax Credit (subject to applicable tax laws and eligibility)',
    gstInvoicePending: 'GST Invoice will be available after order confirmation.',
    businessPurchase: 'Business Purchase',
    manageGstDetails: 'Manage GST Details',
    personalInformation: 'Personal Information',
    businessDetailsTitle: 'Business Details',
    businessDetailsMenu: 'Business Details',
    businessDetailsMenuDesc: 'Manage GST Number & GST Invoice',
    addGstDetails: 'Add GST Details',
    editGst: 'Edit GST',
    removeGst: 'Remove GST',
    removeGstTitle: 'Remove GST Details?',
    removeGstMessage: 'Removing GST will stop GST Invoice generation for future orders.',
    noGstAdded: 'No GST Details Added',
    noGstAddedSubtitle: 'Add your GST number to receive GST invoices on eligible business purchases.',
    gstVerifiedNote: 'Your GST details are verified and ready for invoice generation.',
    verify: 'Verify',
    gstBilling: 'GST & Billing',
    gstinNumber: 'GSTIN NUMBER',
    businessLegalName: 'BUSINESS LEGAL NAME',
    billingCompanyName: 'BILLING COMPANY NAME',
    editDetails: 'Edit Details',
    gstHelp: 'GST invoices help businesses claim input tax credit (ITC) on eligible purchases.',
    saveGstDetails: 'Save GST details for future orders',
    needGstInvoice: 'I need a GST Invoice for this order',
    businessName: 'BUSINESS NAME',
    paymentMethod: 'Payment Method',
    upiPayments: 'UPI PAYMENTS (RECOMMENDED)',
    otherOptions: 'OTHER OPTIONS',
    netBanking: 'Net Banking',
    creditDebitCard: 'Credit / Debit Card',
    payWithUpi: 'Pay with UPI',
    payWithCards: 'Pay with Cards',
    cashOnDelhivery: 'Cash on Delhivery',
    upiSubtitle: 'Google Pay • PhonePe • Paytm • BHIM',
    cardsSubtitle: 'Credit Card • Debit Card',
    cashOnDelhiverySubtitle: 'Pay when your order is delivered.',
    upiDescription: 'Fast and secure UPI payment.',
    cardsDescription: 'Pay securely using your Visa, MasterCard or RuPay card.',
    cashOnDelhiveryDescription: 'Make payment at the time of delivery.',
    upiComingSoonMessage: 'UPI payments will be available soon.',
    cardsComingSoonMessage: 'Card payment integration will be available soon.',
    paymentAvailable: 'Available',
    paymentComingSoon: 'Coming Soon',
    deliveryInstructions: 'Delivery Instructions',
    deliveryInstructionsPlaceholder: 'Enter special instructions for the driver...',
    callOnArrival: 'Call on Arrival',
    leaveAtSecurity: 'Leave at Security',
    heavyVehicleAccess: 'Heavy Vehicle Access',
    redeemLoyaltyPoints: 'Redeem Loyalty Points',
    platinumContractor: 'PLATINUM CONTRACTOR',
    available: 'AVAILABLE',
    value: 'VALUE',
    pointsAvailable: 'points available for redemption',
    eligible: 'ELIGIBLE',
    points: 'POINTS',
    youAreSaving: 'You are saving',
    withLoyaltyRewards: 'with Loyalty Rewards',
    priorityDispatch: 'PRIORITY DISPATCH',
    bulkDiscounts: 'BULK DISCOUNTS',
    shippingLogistics: 'Shipping & Logistics',
    taxes: 'Taxes (GST 18%)',
    totalAmount: 'Total Amount',
    savingWithPricing: 'You are saving ₹2,400 with Corporate Pricing',
    pciCompliant: 'PCI-DSS Compliant Secure Payment',
    qualityGuarantee: '100% Quality Assurance Guarantee',
    payConfirmOrder: 'Pay & Confirm Order',
    orderSuccess: 'Order Success',
    orderConfirmed: 'Order Confirmed',
    deliveryETA: 'DELIVERY ETA',
    assignedWarehouse: 'ASSIGNED WAREHOUSE',
    deliveryTimeline: 'DELIVERY TIMELINE',
    ordered: 'Ordered',
    processing: 'Processing',
    systemValidated: 'System validated and allocated',
    dispatched: 'Dispatched',
    expectedIn: 'Expected in 30 mins',
    delivery: 'Delivery',
    arrivalAtSite: 'Arrival at Site A',
    deliveryAddress: 'DELIVERY ADDRESS',
    viewOrderBtn: 'View Order',
    ordersTitle: 'Orders',
    searchOrders: 'Search premium construction materials...',
    recentOrders: 'Recent Orders',
    bulkDiscount: 'Bulk Discount',
    proTipTitle: 'Optimize Delivery',
    proTipBody: 'Combine Cement and TMT orders to unlock free specialized logistics handling for your site.',
    nextSlot: 'Next available slot: Today, 4:00 PM',
    proTip: 'Pro Tip',
    viewOrderTitle: 'View Order',
    orderId: 'ORDER ID',
    onTheWay: 'ON THE WAY',
    arrivingBy: 'Arriving by',
    orderedMaterials: 'Ordered Materials',
    quantity: 'QUANTITY',
    unitPrice: 'UNIT PRICE',
    deliverySite: 'DELIVERY SITE',
    logisticsLead: 'LOGISTICS LEAD',
    totalPayable: 'TOTAL PAYABLE',
    deliveryFee: 'Delivery Fee',
    totalGst: 'Total GST',
    gstInvoice: 'GST INVOICE',
    generated: 'Generated',
    download: 'Download',
    shareOnWhatsApp: 'Share on WhatsApp',
    loyaltyPointsEarned: 'LOYALTY POINTS EARNED',
    raiseLogisticsIssue: 'Raise a Logistics Issue',
    needImmediateHelp: 'Need immediate help?',
    contactSupport: 'Contact Support',
    mins: 'mins',
    orderDetails: 'Order Details',
    activeDelivery: 'ACTIVE DELIVERY',
    trackingTimeline: 'Tracking Timeline',
    dispatchedStatus: 'Dispatched',
    inTransit: 'In Transit',
    live: 'LIVE',
    estimatedArrival: 'Estimated Arrival',
    support: 'Support',
    orderHistory: 'Order History',
    allOrders: 'All Orders',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    noOrders: 'No orders yet',
    noOrdersSubtitle: 'Your order history will appear here',
    noOrdersFound: 'No orders found',
    noOrdersMatch: 'No orders match "{{query}}"',
    clearSearch: 'Clear Search',
    searchOrdersPlaceholder: 'Search by product, brand, or order ID...',
    reorder: 'Reorder',
    invoice: 'Invoice',
    delivered: 'DELIVERED',
    cancelled: 'CANCELLED',
    inProgress: 'IN PROGRESS',
    notifications: 'Notifications',
    searchNotifications: 'Search alerts, orders, or sites...',
    allNotifications: 'All',
    logisticsFilter: 'Logistics',
    paymentsFilter: 'Payments',
    inventoryFilter: 'Inventory',
    siteComms: 'Site Comms',
    paymentDue: 'PAYMENT DUE',
    stockCritical: 'STOCK CRITICAL',
    siteCommunication: 'SITE COMMUNICATION',
    logisticsUpdate: 'LOGISTICS UPDATE',
    payNow: 'Pay Now',
    refill: 'Refill',
    trackOrder: 'Track Order',
    allCaughtUp: 'All caught up!',
    noNotifications: 'No notifications here',
    markAsRead: 'Mark as Read',
    clearAll: 'Clear All',
    profile: 'Profile',
    editProfile: 'Edit Profile',
    businessDetails: 'Business Details',
    legalEntity: 'LEGAL ENTITY',
    establishmentDate: 'ESTABLISHMENT DATE',
    registeredAddress: 'REGISTERED ADDRESS',
    gstCompliance: 'GST Compliance',
    savedDeliverySites: 'Saved Delivery Sites',
    languageSection: 'Language / भाषा',
    english: 'English',
    englishSubtitle: 'Use app in English',
    hindi: 'हिंदी',
    hindiSubtitle: 'ऐप हिंदी में उपयोग करें',
    languageNote: 'Orders, invoices, notifications and voice search will adapt to your selected language.',
    orderHistoryMenu: 'Order History',
    invoices: 'Invoices',
    loyaltyWallet: 'Loyalty Wallet',
    privacySecurity: 'Privacy & Security',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    paymentMethods: 'Payment Methods',
    primary: 'PRIMARY',
    platinumMember: 'PLATINUM MEMBER',
    personalDetails: 'Personal Details',
    fullName: 'FULL NAME',
    mobileNumber: 'MOBILE NUMBER',
    emailAddress: 'EMAIL ADDRESS',
    gstNumberLabel: 'GST NUMBER',
    businessProfile: 'Business Profile',
    businessType: 'BUSINESS TYPE',
    procurement: 'PROCUREMENT',
    city: 'CITY',
    activeProjectSites: 'Active Project Sites',
    addNewSite: '+ Add New Site',
    saveAllChanges: 'Save All Changes',
    cancelChanges: 'Cancel Changes',
    deliverySites: 'Delivery Sites',
    addNewProjectSite: '+ Add New Project Site',
    warehouseDist: 'Warehouse Dist.',
    estDelivery: 'Est. Delivery',
    siteName: 'Site Name',
    contactPerson: 'Contact Person',
    fullAddress: 'Full Address',
    pincode: 'Pincode',
    gateInstructions: 'Gate Instructions (Optional)',
    saveSite: 'Save Site',
    businessVerification: 'Business Verification',
    gstVerified: 'GST Verified',
    complianceScore: 'Compliance Score',
    entityInformation: 'Entity Information',
    pan: 'PAN',
    registrationDate: 'REGISTRATION DATE',
    jurisdiction: 'JURISDICTION',
    gstCertificate: 'GST Certificate',
    downloadPdf: 'Download PDF',
    invoicesTitle: 'Invoices',
    searchInvoice: 'Search Invoice ID, Site, or Vendor',
    all: 'All',
    unpaid: 'Unpaid',
    overdue: 'Overdue',
    totalAmountLabel: 'TOTAL AMOUNT',
    viewTimeline: 'View Timeline',
    syncGstTitle: 'Sync GST Returns Seamlessly',
    syncGstSubtitle: 'Automate your GSTR-1 and GSTR-3B filings by connecting your Tally or ERP software directly with Bajriwala.',
    connectErp: 'Connect ERP',
    loyaltyRewards: 'Loyalty Rewards',
    premiumTier: 'PREMIUM TIER',
    platinumContractorTitle: 'Platinum\nContractor',
    totalPoints: 'TOTAL POINTS',
    cashbackEarned: 'CASHBACK EARNED',
    membershipProgress: 'Membership Progress',
    spendMore: 'Spend ₹1.2L more to reach Diamond',
    totalSpend: 'Total Spend',
    diamondTier: 'Diamond Tier',
    viewTierBenefits: 'View Tier Benefits',
    proKnight: 'PRO KNIGHT',
    earn2xPoints: 'Earn 2x Points on Steel',
    earn2xSubtitle: 'Order over 50 metric tons of Tata Tiscon this week to unlock double milestone credits.',
    redeemRewardsTitle: 'Redeem Rewards',
    redeemSubtitle: 'Premium benefits tailored for your projects',
    hotDeal: 'Hot Deal',
    platinumOnly: 'Platinum Only',
    canRedeem: '✓ You can redeem this',
    needMoreCP: 'more CP needed',
    activityHistory: 'Activity History',
    downloadStatement: 'Download Statement',
    supportDisputes: 'Support & Disputes',
    history: 'History',
    newTicket: '+ New Ticket',
    activeDispute: 'ACTIVE DISPUTE',
    inReview: 'In Review',
    resolutionSteps: 'Resolution Steps',
    ticketRaised: 'Ticket Raised',
    evidenceReceived: 'Evidence Received',
    underInvestigation: 'Under Investigation',
    resolutionPending: 'Resolution Pending',
    fileNewDispute: 'File New Dispute',
    reportWrongItem: 'Report Wrong Item',
    damagedGoods: 'Damaged Goods',
    missingQuantity: 'Missing Quantity',
    refundRequest: 'Refund Request',
    uploadEvidence: 'Upload Evidence',
    uploadEvidenceSubtitle: 'Please provide high-resolution photos or videos of the damaged items.',
    dragDropFiles: 'Drag and drop media files',
    supportsFormats: 'Supports JPG, PNG, MP4 up to 50MB',
    selectFiles: 'Select Files',
    liveChat: 'Live Chat',
    liveChatSubtitle: 'Response in < 2 min',
    callSupportLabel: 'Call Support',
    callSupportSubtitle: 'Direct Line Available',
    voiceAssistant: 'Voice Assistant',
    activeConnection: 'Active Connection',
    tapToSpeak: 'Tap to speak',
    listening: 'Listening...',
    findingResults: 'Finding results...',
    hereIsWhatIFound: 'Here\'s what I found',
    trySaying: 'Try saying',
    orderCementBags: 'Order cement bags',
    steelPricesToday: 'Steel prices today',
    trackMyOrder: 'Track my order',
    emergencyDelivery: 'Emergency delivery',
    result: 'RESULT',
    tryAgain: 'Try again',
    searchTitle: 'Search',
    searchBajriwala: 'Search Bajriwala',
    recentSearches: 'Recent Searches',
    searchResults: 'Search Results',
    frequentlyPurchasedTogether: 'FREQUENTLY PURCHASED TOGETHER',
    recentlyViewed: 'RECENTLY VIEWED',
    noResultsFor: 'No results for',
    trySearching: 'Try searching cement, steel, sand, bricks',
    trySearchingFor: 'Try searching for:',
    popularCategories: 'Popular Categories',
    resultsFor: 'results for',
    sortBy: 'Sort by',
    relevance: 'Relevance',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    newestFirst: 'Newest First',
    oldestFirst: 'Oldest First',
    nameAZ: 'Name: A to Z',
    browseAllCategories: 'Browse All Categories →',
    completeProfileTitle: 'Complete Your Profile',
    completeProfileSubtitle: 'Tell us your name and preferred language to get started.',
    companyName: 'Company Name',
    companyNamePlaceholder: 'Enter your company name',
    gstPlaceholder: '22AAAAA0000A1Z5',
    chooseLanguage: 'Choose Your Preferred Language',
    languageSubtitle: 'Continue in the language you\'re most comfortable with.',
    hindiLink: 'अपनी पसंदीदा भाषा चुनें',
    recommendedRegion: 'Recommended based on your region',
    continueInEnglish: 'Continue in English',
    continueInHindi: 'हिंदी में जारी रखें',
    isoSecurity: 'ISO 27001 CERTIFIED ENTERPRISE SECURITY',
    continueBtn: 'Continue',
    deliveryLocation: 'Delivery Location',
    searchSiteAddress: 'Search for Site Address',
    preciseGpsPinning: 'Precise GPS Pinning',
    manageProjects: 'Manage your active construction projects',
    registerDeliveryPoint: 'Register a new delivery point',
    industrialPrecision: 'Industrial Precision',
    industrialPrecisionDesc: 'Our system uses high-accuracy geo-fencing to ensure materials are dropped exactly where your crew needs them.',
    siteLogisticsSupport: 'Site Logistics Support',
    siteLogisticsSupportDesc: 'Need specific gate entry instructions? Add them to your site profile and our drivers will follow every protocol.',
    allowFetchLocation: 'Allow Fetch Location',
    addressLine1: 'Address Line 1',
    drawerHome: 'Home',
    drawerCatalog: 'Product Catalog',
    drawerOrders: 'My Orders',
    drawerTrackDeliveries: 'Track Deliveries',
    drawerSavedSites: 'Saved Sites',
    drawerGstInvoices: 'GST Invoices',
    drawerLoyalty: 'Loyalty & Rewards',
    drawerNotifications: 'Notifications',
    drawerProcurementTools: 'PROCUREMENT TOOLS',
    drawerEmergencyOrders: 'Emergency Orders',
    drawerBulkProcurement: 'Bulk Procurement',
    drawerOrderHistory: 'Order History',
    drawerSupport: 'SUPPORT',
    drawerHelpCenter: 'Help Center',
    drawerWhatsAppSupport: 'WhatsApp Support',
    drawerRaiseTicket: 'Raise Ticket',
    drawerPreferences: 'PREFERENCES',
    drawerLanguage: 'Language',
    drawerPrivacy: 'Privacy & Security',
    drawerTerms: 'Terms & Conditions',
    drawerLogout: 'Logout',
    drawerVersion: 'Bajriwala v2.4.0',
    drawerLogoutTitle: 'Logout',
    drawerLogoutMessage: 'Are you sure you want to logout?',
    drawerLogoutConfirm: 'Logout',
    drawerLogoutCancel: 'Cancel',
    filterOrders: 'Filter Orders',
    filterStatus: 'STATUS',
    filterDate: 'DATE',
    filterAll: 'All',
    filterActive: 'Active',
    filterDelivered: 'Delivered',
    filterCancelled: 'Cancelled',
    filterAllTime: 'All Time',
    filterToday: 'Today',
    filterThisWeek: 'This Week',
    filterThisMonth: 'This Month',
    apply: 'Apply',
    minUnits: 'Min. {{count}} units',
    goBack: 'Go Back',
    productNotFound: 'Product Not Found',
    noProductsFound: 'No Products Found',
    unableToLoadProducts: 'Unable to load products.',
    unableToLoadCategories: 'Unable to load categories.',
    locationAccessRequired: 'Location Access Required',
    bulkProcurement: 'Bulk Procurement',
    goldMember: 'Gold Member',
    silverMember: 'Silver Member',
    scheduledDeliveryLabel: 'Scheduled Delivery',
    etaLabel: 'ETA',
    orderedStep: 'Ordered',
    processingStep: 'Processing',
    shippingStep: 'Shipping',
    deliveryStep: 'Delivery',
    confirmed: 'Confirmed',
    catalogLabel: 'Catalog',
    applied: 'Applied',
    maxLabel: 'Max',
    loyaltyRedemption: 'Loyalty Redemption',
    addPaymentMethod: 'Add Payment Method',
    contactLink: 'Contact',
    readAction: 'Read',
    markRead: 'Mark Read',
    proTipEfficiencyTitle: 'Maximize Procurement Efficiency',
    proTipEfficiencyBody: 'Combine orders from the same warehouse to reduce delivery fees and unlock bulk pricing tiers automatically.',
    privacyBiometric: 'Biometric Login',
    privacyBiometricDesc: 'Use Face ID or fingerprint to secure your account',
    privacyTwoFactor: 'Two-Factor Authentication',
    privacyTwoFactorDesc: 'Add an extra layer of security with OTP verification',
    privacyAnalytics: 'Usage Analytics',
    privacyAnalyticsDesc: 'Help us improve by sharing anonymous usage data',
    privacyDataTitle: 'Data & Privacy',
    privacyDataBody: 'Your business data is encrypted and never shared with third parties without consent.',
    invoiceDetails: 'Invoice Details',
    billedFrom: 'Billed From',
    billedTo: 'Billed To',
    itemsOrdered: 'Items Ordered',
    timeline: 'Timeline',
    downloadPdfShort: 'Download PDF',
    termsSection: 'Terms & Conditions',
    trackDeliveries: 'Track Deliveries',
    trackDeliveriesEmpty: 'No active deliveries to track',
    loyaltyRewardsTitle: 'Loyalty Rewards',
    availablePoints: 'Available Points',
    walletBalance: 'Wallet Balance',
    recentActivity: 'Recent Activity',
    addPaymentMethodLabel: 'Add Payment Method',
    invoiceGenerated: 'Invoice Generated',
    paymentReceived: 'Payment Received',
    gstFiled: 'GST Filed',
    whatsapp: 'WhatsApp',
    pdf: 'PDF',
    paidFilter: 'Paid',
    contactPersonLabel: 'Contact Person',
    editDeliverySite: 'Edit Delivery Site',
    editProjectSite: 'Edit Project Site',
    pinLocation: 'Pin Location',
    cancelLabel: 'Cancel',
    profileSaved: 'Profile saved successfully',
    comingSoon: 'Coming soon',
    online: 'Online',
    chatPlaceholder: 'Type a message below to start chatting',
    splashTagline: 'Construction Materials\nDelivered Fast',
    enterpriseSecureNetwork: 'ENTERPRISE SECURE NETWORK',
    welcomeBack: 'Welcome Back, Builder',
    loginSubtitle: 'Enter your mobile number to manage site logistics and procurement.',
    loginMobileLabel: 'Mobile Number',
    loginBtn: 'Login',
    trustedBy: 'Trusted by 500+ Contractors across Delhi',
    contractorsIndia: 'Contractors across Delhi',
    helpCenter: 'Help Center',
    privacyPolicy: 'Privacy Policy',
    termsLink: 'Terms',
    copyrightNotice: '© 2024 Bajriwala India Private Limited. All rights reserved.',
    verifyIdentity: 'Verify Your Identity',
    otpSentTo: "We've sent a 6-digit code to",
    changeNumber: 'Change Number',
    resendCodeIn: 'Resend code in',
    verifyContinue: 'Verify & Continue',
    secureEncryption: 'SECURE 256-BIT AES ENCRYPTION',
    selectRole: 'Select Your Role',
    personalizeExperience: 'Personalize your BajriPro experience',
    roleIndividual: 'Individual',
    roleIndividualDesc: 'Order materials for personal or home projects.',
    roleContractor: 'Contractor',
    roleContractorDesc: 'Manage site logistics, labor, and procurement.',
    roleInterior: 'Interior Designer / Architect',
    roleInteriorDesc: 'Source premium materials and manage interiors.',
    roleBuilder: 'Builder / Developer',
    roleBuilderDesc: 'Handle large-scale construction and projects.',
    redeemPointsNextOrder: 'Redeem points on your next order',
    totalAmountPayable: 'TOTAL AMOUNT PAYABLE',
    inclusiveTaxes: 'Inclusive of all taxes',
    shareOnWhatsAppShort: 'Share on WhatsApp',
    loyaltyPointsProgress: '450 / 600 pts',
    lastOrderedTmt: 'Last ordered: 3 days ago',
    lastOrderedPvc: 'Last ordered: 1 week ago',
  },
  hi: {
    tabHome: 'होम',
    tabCatalog: 'कैटलॉग',
    tabOrders: 'ऑर्डर',
    tabAccount: 'खाता',
    back: 'वापस',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    confirm: 'पुष्टि करें',
    loading: 'लोड हो रहा है...',
    viewAll: 'सभी देखें',
    search: 'खोजें',
    filter: 'फ़िल्टर',
    sort: 'क्रम बदलें',
    close: 'बंद करें',
    done: 'हो गया',
    next: 'अगला',
    submit: 'जमा करें',
    retry: 'पुनः प्रयास',
    or: 'या',
    free: 'मुफ़्त',
    paid: 'भुगतान हो गया',
    pending: 'लंबित',
    verified: 'सत्यापित',
    active: 'सक्रिय',
    optional: 'वैकल्पिक',
    goodMorning: 'सुप्रभात',
    goodAfternoon: 'नमस्ते',
    goodEvening: 'शुभ संध्या',
    homeSubtitle: 'आज आसमान छूने के लिए तैयार हैं?',
    searchMaterials: 'सामग्री खोजें',
    searchPlaceholder: 'प्रीमियम निर्माण सामग्री खोजें...',
    twoHourDelivery: '2 घंटे में डिलीवरी',
    heroBannerTitle: 'आपकी साइट की हर जरूरत — तेज़ डिलीवरी',
    shopNow: 'अभी खरीदें',
    bulkInquiry: 'थोक पूछताछ',
    platinumTier: 'प्लेटिनम स्तर',
    loyaltyProgress: 'लॉयल्टी प्रगति',
    platinumNext: 'प्लेटिनम अगला',
    earnPoints: 'अगले ऑर्डर पर मुफ्त लॉजिस्टिक्स के लिए 150 और पॉइंट अर्जित करें।',
    materialCategories: 'सामग्री श्रेणियाँ',
    viewCat: 'सभी देखें',
    criticalShortage: 'गंभीर प्रोजेक्ट कमी?',
    criticalSubtitle: '90 मिनट में जरूरी सामग्री साइट पर। 24/7 लॉजिस्टिक्स आपकी सेवा में।',
    emergencyOrder: 'आपातकालीन ऑर्डर',
    emergencyDeliveryTitle: 'आपातकालीन डिलीवरी',
    emergencyDeliverySubtitle: 'साइट पर कमी? आवश्यक सामग्री तेज़ी से मंगाएं — 24/7 लॉजिस्टिक्स।',
    emergencyEta: '30–90 मिनट',
    orderNow: 'अभी ऑर्डर करें',
    membershipBadge: 'मेंबरशिप',
    membershipTitle: 'बजरीवाला मेंबरशिप',
    membershipSubtitle: 'अपनी साइटों के लिए प्रीमियम बचत और लाभ अनलॉक करें।',
    membershipPerYear: 'वर्ष',
    membershipExtraDiscount: 'अतिरिक्त छूट',
    membershipFreeDelivery: 'मुफ़्त डिलीवरी',
    membershipBulkDiscounts: 'बल्क छूट',
    membershipInternationalTrips: 'अंतरराष्ट्रीय यात्राएं',
    membershipLuckyDraw: 'लकी ड्रॉ',
    membershipLoyaltyPoints: 'लॉयल्टी पॉइंट्स',
    joinNow: 'अभी जुड़ें',
    membershipJoinMock: 'मेंबरशिप जल्द आ रही है। आपको सूचित किया जाएगा!',
    bulkProcurementSection: 'बल्क खरीद',
    bulkProcurementCardTitle: 'बल्क खरीद लाभ',
    bulkProcurementCardSubtitle: 'बड़े निर्माण ऑर्डर के लिए विशेष लाभ अनलॉक करें।',
    unlock: 'अनलॉक',
    bulkUnlockDiscount: '15% तक छूट अनलॉक करें',
    bulkUnlockTrips: 'अंतरराष्ट्रीय यात्राएं',
    bulkUnlockLuckyDraw: 'लकी ड्रॉ',
    bulkUnlockLoyalty: 'लॉयल्टी पॉइंट्स',
    unlockBenefits: 'लाभ अनलॉक करें',
    knowMore: 'और जानें',
    customerTestimonials: 'ग्राहक प्रशंसापत्र',
    customerTestimonialsSubtitle:
      'भारत भर के ठेकेदारों, बिल्डरों और घर मालिकों द्वारा विश्वसनीय।',
    loadingTestimonial: 'प्रशंसापत्र लोड हो रहा है...',
    unableToPlayVideo: 'वीडियो चलाने में असमर्थ',
    skipForNow: 'छोड़ें',
    skipGst: 'छोड़ें →',
    skipProfile: 'छोड़ें',
    addGstNumber: '+ GST नंबर जोड़ें',
    gstSkippedLabel: 'GST अभी के लिए छोड़ दिया गया',
    gstOptionalHint:
      'यदि आपके पास GST प्रमाणपत्र है, तो बिज़नेस प्राइसिंग और GST चालान अनलॉक करने के लिए इसे जोड़ें। आप इसे अभी छोड़ सकते हैं और बाद में प्रोफ़ाइल में जोड़ सकते हैं।',
    hardware: 'हार्डवेयर',
    cantFindProduct: 'अपना उत्पाद नहीं मिल रहा?',
    speakToExpert: 'हमारे मटेरियल एक्सपर्ट से बात करें',
    talkToExpert: 'एक्सपर्ट से बात करें',
    expertSheetSubtitle: 'बताएं आपको क्या चाहिए — हमारा एक्सपर्ट जल्द कॉल करेगा।',
    yourName: 'आपका नाम',
    namePlaceholder: 'अपना नाम दर्ज करें',
    whatDoYouNeed: 'आपको क्या चाहिए?',
    needPlaceholder: 'जैसे 200 बैग OPC 53...',
    requestCallback: 'कॉलबैक का अनुरोध',
    expertRequestSent: 'अनुरोध प्राप्त',
    expertRequestBody: 'हमारा मटेरियल एक्सपर्ट जल्द संपर्क करेगा। (मॉक)',
    bulkPriceBadge: 'बल्क प्राइस',
    bulkPricingTitle: 'बल्क प्राइसिंग',
    deliveryEtaLabel: 'डिलीवरी',
    onlyXLeft: 'केवल {count} बचे',
    add: 'जोड़ें',
    added: 'जोड़ा',
    addedToCartBtn: 'जोड़ा गया ✓',
    updateCart: 'कार्ट अपडेट करें',
    wallet: 'वॉलेट',
    refundHistory: 'रिफंड इतिहास',
    walletBalanceHint: 'उपलब्ध होने पर चेकआउट पर वॉलेट बैलेंस उपयोग करें।',
    walletComingSoonBody: 'टॉप-अप, कैशबैक और ट्रांसफर जल्द आ रहे हैं।',
    completed: 'पूर्ण',
    failed: 'विफल',
    deliveryCharge: 'डिलीवरी',
    loadingCharges: 'लोडिंग शुल्क',
    unloadingCharges: 'अनलोडिंग शुल्क',
    walletDeduction: 'वॉलेट',
    bikeDelivery: 'बाइक डिलीवरी',
    bikeDeliveryFree: 'मुफ़्त',
    paymentWallet: 'वॉलेट',
    paymentUpi: 'UPI',
    walletDisabledHint: 'वॉलेट उपलब्ध नहीं (बैलेंस ₹0)',
    smartReorder: 'स्मार्ट री-ऑर्डर',
    lastOrders: 'पिछले ऑर्डर',
    lastOrdersSubtitle: 'आपके पहले ऑर्डर की वस्तुएं',
    lastOrdered: 'अंतिम ऑर्डर',
    viewProduct: 'देखें',
    recommendedProducts: 'अनुशंसित उत्पाद',
    recommendedForYou: 'आपके लिए अनुशंसित',
    recommendedSubtitle: 'आपकी ब्राउज़िंग और खरीदारी के आधार पर उत्पाद',
    recommendedBecause: 'अनुशंसित क्योंकि',
    recommendedPreviouslyOrdered: 'पहले ऑर्डर किया',
    recommendedPopularNearYou: 'आपके पास लोकप्रिय',
    recommendedFrequentlyBought: 'अक्सर खरीदे जाते हैं',
    noLastOrdersPrompt: 'अभी तक कोई ऑर्डर नहीं',
    noLastOrdersSubtitle: 'आपकी पिछली ऑर्डर की वस्तुएं यहाँ दिखेंगी',
    shop: 'खरीदें',
    callDriver: 'ड्राइवर को कॉल करें',
    redeemRewards: 'रिवॉर्ड रिडीम करें',
    progressToPlatinum: 'प्लेटिनम की ओर प्रगति',
    deliveryIn: 'डिलीवरी',
    enRoute: 'रास्ते में',
    proStatus: 'प्रो स्थिति',
    cement: 'सीमेंट',
    steel: 'स्टील',
    sand: 'रेत',
    bricksAndMasonry: 'ईंट और चिनाई',
    greyFillSand: 'ग्रे फिल सैंड',
    stoneChip: 'स्टोन चिप',
    aggregates: 'एग्रीगेट्स',
    adhesives: 'एडहेसिव',
    wallRepair: 'वॉल रिपेयर',
    waterproofing: 'वॉटरप्रूफिंग',
    quickRepair: 'क्विक रिपेयर',
    putty: 'पुट्टी',
    productsCount: '{count} उत्पाद',
    loginMobileInvalid: 'कृपया एक वैध 10-अंकीय मोबाइल नंबर दर्ज करें।',
    plumbing: 'प्लंबिंग',
    electrical: 'बिजली',
    catalogTitle: 'सटीक खरीदारी',
    catalogSubtitle: 'उच्च-ग्रेड औद्योगिक सामग्री के हमारे चयनित संग्रह के साथ अपनी निर्माण साइट इन्वेंटरी को सुव्यवस्थित करें।',
    bulkProcurementTitle: 'थोक खरीदारी छूट',
    bulkProcurementSubtitle: 'मिश्रित सामग्री कंटेनर लोड पर 15% तक की छूट पाएं।',
    inquireNow: 'अभी पूछताछ करें',
    priorityExpress: 'प्राथमिकता एक्सप्रेस',
    priorityExpressSubtitle: 'सभी मुख्य इन्वेंटरी आइटम के लिए गारंटीड उसी दिन डिलीवरी।',
    searchCatalog: 'सीमेंट, स्टील, ईंट खोजें...',
    readyForDispatch: 'भेजने के लिए तैयार',
    inStock: 'स्टॉक में है',
    limitedStock: 'सीमित स्टॉक',
    outOfStock: 'स्टॉक खत्म',
    trending: 'ट्रेंडिंग',
    popular: 'लोकप्रिय',
    new: 'नया',
    bulkSavings: 'थोक बचत',
    getReady: 'तैयार हो जाएं',
    retailPrice: 'खुदरा मूल्य',
    bulkPrice: 'थोक मूल्य',
    minOrder: 'न्यूनतम',
    grade: 'ग्रेड',
    perBag: 'प्रति बैग',
    perTon: 'प्रति टन',
    perPiece: 'प्रति टुकड़ा',
    addToCart: 'कार्ट में जोड़ें',
    viewOrder: 'ऑर्डर देखें',
    details: 'विवरण',
    productDetail: 'उत्पाद विवरण',
    technicalSpecs: 'तकनीकी विशेषताएं',
    financials: 'वित्तीय',
    gstInvoiceReady: 'GST चालान तैयार',
    shipping: 'शिपिंग',
    flatbedLogistics: 'फ्लैटबेड लॉजिस्टिक्स',
    gradeLabel: 'ग्रेड',
    settingTime: 'सेटिंग समय',
    strength: 'मजबूती',
    compression: 'दबाव',
    superiorDurability: 'उच्च टिकाऊपन',
    projectSiteSelection: 'प्रोजेक्ट साइट चयन',
    totalSubtotal: 'कुल उपयोग',
    pricingSummary: 'मूल्य सारांश',
    baseRate: 'आधार दर',
    subtotal: 'उप-कुल',
    logistics: 'लॉजिस्टिक्स (एक्सप्रेस)',
    gst18: 'GST (18%)',
    estimatedTotal: 'अनुमानित कुल',
    quickQuote: 'त्वरित कोटेशन',
    pricesLocked: 'कीमतें 15 मिनट के लिए लॉक हैं। अंतिम वजन प्रमाण साइट पर दिया जाएगा।',
    deliveryLogistics: 'डिलीवरी और लॉजिस्टिक्स',
    availableNow: 'अभी उपलब्ध',
    deliveryIn24: '2–4 घंटे में डिलीवरी',
    nearestWarehouse: 'निकटतम गोदाम',
    priority: 'प्राथमिकता',
    standard: 'सामान्य',
    scheduled: 'निर्धारित',
    chooseSlot: 'स्लॉट चुनें',
    siteReady: 'साइट-तैयार',
    logisticsBreakdown: 'लॉजिस्टिक्स विवरण',
    heavyLoad: 'भारी भार',
    distance: 'दूरी',
    unloadingHelp: 'अनलोडिंग सहायता',
    fastestDelivery: 'सबसे तेज़ डिलीवरी',
    materialsAvailable: 'सामग्री उपलब्ध है',
    warehouse: 'गोदाम',
    vehicle: 'वाहन',
    frequentlyBought: 'अक्सर एक साथ खरीदे जाते हैं',
    addBundle: 'बंडल जोड़ें',
    yourCart: 'आपका कार्ट',
    activeItems: 'सक्रिय आइटम',
    saveForLater: 'बाद के लिए सहेजें',
    buildProPoints: 'बजरीप्रो पॉइंट',
    balance: 'बैलेंस',
    usePointsToSave: '2,500 पॉइंट उपयोग करके ₹500 बचाएं',
    orderSummary: 'ऑर्डर सारांश',
    itemsTotal: 'आइटम कुल',
    deliveryCharges: 'डिलीवरी शुल्क',
    loyaltyDiscount: 'लॉयल्टी छूट',
    grandTotal: 'कुल राशि',
    totalPrice: 'कुल मूल्य',
    proceedCheckout: 'चेकआउट पर जाएं',
    secureCheckout: 'सुरक्षित चेकआउट',
    emptyCart: 'आपका कार्ट खाली है',
    emptyCartSubtitle: 'शुरू करने के लिए सामग्री जोड़ें',
    browseCatalog: 'कैटलॉग देखें',
    checkout: 'चेकआउट',
    deliveryDestination: 'डिलीवरी गंतव्य',
    change: 'बदलें',
    scheduledDelivery: 'निर्धारित डिलीवरी',
    gstNumber: 'GST नंबर',
    billDetails: 'बिल विवरण',
    gstInvoiceCardTitle: 'GST चालान',
    gstInvoiceCardSubtitle: 'व्यावसायिक खरीद पर GST चालान प्राप्त करने के लिए GST विवरण जोड़ें',
    gstInvoiceApplied: 'GST चालान लागू',
    gstInvoiceAppliedNote: 'चालान आपके GSTIN का उपयोग करके जेनरेट किया जाएगा।',
    gstInvoiceEnabled: 'GST चालान सक्षम',
    businessInvoiceEnabled: 'व्यावसायिक चालान सक्षम',
    gstSuccessBannerTitle: 'व्यावसायिक GST सत्यापित',
    gstSuccessBannerSubtitle: 'व्यावसायिक प्राइसिंग अनलॉक',
    gstBusinessInvoiceEnabled: 'GST व्यावसायिक चालान सक्षम',
    gstBusinessInvoiceEligible: 'व्यावसायिक टैक्स चालान के लिए पात्र',
    gstBusinessDiscountNote: 'मानक B2B प्राइसिंग · इनपुट टैक्स क्रेडिट पात्र',
    totalBeforeGstDiscount: 'GST छूट से पहले कुल',
    gstBusinessDiscountApplied: 'GST व्यावसायिक छूट लागू',
    withVerifiedGstPricing: 'सत्यापित GST प्राइसिंग के साथ',
    businessBenefits: 'व्यावसायिक लाभ',
    gstBenefitInvoice: 'GST चालान',
    gstBenefitAccounting: 'तेज़ लेखांकन',
    gstBenefitHistory: 'व्यावसायिक खरीद इतिहास',
    gstBenefitItc: 'इनपुट टैक्स क्रेडिट (लागू कर कानूनों और पात्रता के अधीन)',
    gstInvoicePending: 'ऑर्डर पुष्टि के बाद GST चालान उपलब्ध होगा।',
    businessPurchase: 'व्यावसायिक खरीद',
    manageGstDetails: 'GST विवरण प्रबंधित करें',
    personalInformation: 'व्यक्तिगत जानकारी',
    businessDetailsTitle: 'व्यवसाय विवरण',
    businessDetailsMenu: 'व्यवसाय विवरण',
    businessDetailsMenuDesc: 'GST नंबर और GST चालान प्रबंधित करें',
    addGstDetails: 'GST विवरण जोड़ें',
    editGst: 'GST संपादित करें',
    removeGst: 'GST हटाएं',
    removeGstTitle: 'GST विवरण हटाएं?',
    removeGstMessage: 'GST हटाने से भविष्य के ऑर्डर के लिए GST चालान जेनरेशन बंद हो जाएगी।',
    noGstAdded: 'कोई GST विवरण नहीं जोड़ा गया',
    noGstAddedSubtitle: 'पात्र व्यावसायिक खरीद पर GST चालान प्राप्त करने के लिए अपना GST नंबर जोड़ें।',
    gstVerifiedNote: 'आपके GST विवरण सत्यापित हैं और चालान जेनरेशन के लिए तैयार हैं।',
    verify: 'सत्यापित करें',
    gstBilling: 'GST और बिलिंग',
    gstinNumber: 'GSTIN नंबर',
    businessLegalName: 'व्यवसाय का कानूनी नाम',
    billingCompanyName: 'बिलिंग कंपनी नाम',
    editDetails: 'विवरण संपादित करें',
    gstHelp: 'GST चालान व्यवसायों को इनपुट टैक्स क्रेडिट (ITC) दावा करने में मदद करते हैं।',
    saveGstDetails: 'भविष्य के ऑर्डर के लिए GST विवरण सहेजें',
    needGstInvoice: 'मुझे इस ऑर्डर के लिए GST चालान चाहिए',
    businessName: 'व्यवसाय का नाम',
    paymentMethod: 'भुगतान विधि',
    upiPayments: 'UPI भुगतान (अनुशंसित)',
    otherOptions: 'अन्य विकल्प',
    netBanking: 'नेट बैंकिंग',
    creditDebitCard: 'क्रेडिट / डेबिट कार्ड',
    payWithUpi: 'UPI से भुगतान करें',
    payWithCards: 'कार्ड से भुगतान करें',
    cashOnDelhivery: 'कैश ऑन डिल्हीवरी',
    upiSubtitle: 'Google Pay • PhonePe • Paytm • BHIM',
    cardsSubtitle: 'क्रेडिट कार्ड • डेबिट कार्ड',
    cashOnDelhiverySubtitle: 'ऑर्डर डिलीवर होने पर भुगतान करें।',
    upiDescription: 'तेज़ और सुरक्षित UPI भुगतान।',
    cardsDescription: 'Visa, MasterCard या RuPay कार्ड से सुरक्षित भुगतान करें।',
    cashOnDelhiveryDescription: 'डिलीवरी के समय भुगतान करें।',
    upiComingSoonMessage: 'UPI भुगतान जल्द उपलब्ध होगा।',
    cardsComingSoonMessage: 'कार्ड भुगतान जल्द उपलब्ध होगा।',
    paymentAvailable: 'उपलब्ध',
    paymentComingSoon: 'जल्द आ रहा है',
    deliveryInstructions: 'डिलीवरी निर्देश',
    deliveryInstructionsPlaceholder: 'ड्राइवर के लिए विशेष निर्देश दर्ज करें...',
    callOnArrival: 'आने पर कॉल करें',
    leaveAtSecurity: 'सुरक्षा पर छोड़ें',
    heavyVehicleAccess: 'भारी वाहन पहुंच',
    redeemLoyaltyPoints: 'लॉयल्टी पॉइंट रिडीम करें',
    platinumContractor: 'प्लेटिनम ठेकेदार',
    available: 'उपलब्ध',
    value: 'मूल्य',
    pointsAvailable: 'पॉइंट रिडीम के लिए उपलब्ध',
    eligible: 'पात्र',
    points: 'पॉइंट',
    youAreSaving: 'आप बचत कर रहे हैं',
    withLoyaltyRewards: 'लॉयल्टी रिवॉर्ड से',
    priorityDispatch: 'प्राथमिकता प्रेषण',
    bulkDiscounts: 'थोक छूट',
    shippingLogistics: 'शिपिंग और लॉजिस्टिक्स',
    taxes: 'कर (GST 18%)',
    totalAmount: 'कुल राशि',
    savingWithPricing: 'आप कॉर्पोरेट मूल्य निर्धारण से ₹2,400 बचा रहे हैं',
    pciCompliant: 'PCI-DSS अनुपालन सुरक्षित भुगतान',
    qualityGuarantee: '100% गुणवत्ता आश्वासन गारंटी',
    payConfirmOrder: 'भुगतान करें और ऑर्डर की पुष्टि करें',
    orderSuccess: 'ऑर्डर सफल',
    orderConfirmed: 'ऑर्डर की पुष्टि हो गई',
    deliveryETA: 'डिलीवरी समय',
    assignedWarehouse: 'नियुक्त गोदाम',
    deliveryTimeline: 'डिलीवरी समयरेखा',
    ordered: 'ऑर्डर किया',
    processing: 'प्रक्रिया में',
    systemValidated: 'सिस्टम द्वारा सत्यापित और आवंटित',
    dispatched: 'भेजा गया',
    expectedIn: '30 मिनट में अपेक्षित',
    delivery: 'डिलीवरी',
    arrivalAtSite: 'साइट A पर आगमन',
    deliveryAddress: 'डिलीवरी पता',
    viewOrderBtn: 'ऑर्डर देखें',
    ordersTitle: 'ऑर्डर',
    searchOrders: 'प्रीमियम निर्माण सामग्री खोजें...',
    recentOrders: 'हाल के ऑर्डर',
    bulkDiscount: 'थोक छूट',
    proTipTitle: 'डिलीवरी अनुकूलित करें',
    proTipBody: 'मुफ्त विशेष लॉजिस्टिक्स के लिए सीमेंट और TMT ऑर्डर एक साथ करें।',
    nextSlot: 'अगला स्लॉट: आज, शाम 4:00 बजे',
    proTip: 'प्रो टिप',
    viewOrderTitle: 'ऑर्डर देखें',
    orderId: 'ऑर्डर आईडी',
    onTheWay: 'रास्ते में',
    arrivingBy: 'आने का समय',
    orderedMaterials: 'ऑर्डर की गई सामग्री',
    quantity: 'मात्रा',
    unitPrice: 'इकाई मूल्य',
    deliverySite: 'डिलीवरी साइट',
    logisticsLead: 'लॉजिस्टिक्स प्रमुख',
    totalPayable: 'कुल देय',
    deliveryFee: 'डिलीवरी शुल्क',
    totalGst: 'कुल GST',
    gstInvoice: 'GST चालान',
    generated: 'बनाया गया',
    download: 'डाउनलोड',
    shareOnWhatsApp: 'WhatsApp पर शेयर करें',
    loyaltyPointsEarned: 'अर्जित लॉयल्टी पॉइंट',
    raiseLogisticsIssue: 'लॉजिस्टिक्स समस्या दर्ज करें',
    needImmediateHelp: 'तत्काल सहायता चाहिए?',
    contactSupport: 'सहायता से संपर्क करें',
    mins: 'मिनट',
    orderDetails: 'ऑर्डर विवरण',
    activeDelivery: 'सक्रिय डिलीवरी',
    trackingTimeline: 'ट्रैकिंग समयरेखा',
    dispatchedStatus: 'भेजा गया',
    inTransit: 'रास्ते में',
    live: 'लाइव',
    estimatedArrival: 'अनुमानित आगमन',
    support: 'सहायता',
    orderHistory: 'ऑर्डर इतिहास',
    allOrders: 'सभी ऑर्डर',
    thisMonth: 'इस महीने',
    lastMonth: 'पिछले महीने',
    noOrders: 'अभी तक कोई ऑर्डर नहीं',
    noOrdersSubtitle: 'आपका ऑर्डर इतिहास यहाँ दिखेगा',
    noOrdersFound: 'कोई ऑर्डर नहीं मिला',
    noOrdersMatch: '"{{query}}" से कोई ऑर्डर मेल नहीं खाता',
    clearSearch: 'खोज साफ़ करें',
    searchOrdersPlaceholder: 'उत्पाद, ब्रांड या ऑर्डर आईडी से खोजें...',
    reorder: 'दोबारा ऑर्डर करें',
    invoice: 'चालान',
    delivered: 'डिलीवर हो गया',
    cancelled: 'रद्द',
    inProgress: 'प्रगति में',
    notifications: 'सूचनाएं',
    searchNotifications: 'अलर्ट, ऑर्डर या साइट खोजें...',
    allNotifications: 'सभी',
    logisticsFilter: 'लॉजिस्टिक्स',
    paymentsFilter: 'भुगतान',
    inventoryFilter: 'इन्वेंटरी',
    siteComms: 'साइट संचार',
    paymentDue: 'भुगतान बकाया',
    stockCritical: 'स्टॉक कम',
    siteCommunication: 'साइट संचार',
    logisticsUpdate: 'लॉजिस्टिक्स अपडेट',
    payNow: 'अभी भुगतान करें',
    refill: 'फिर से भरें',
    trackOrder: 'ऑर्डर ट्रैक करें',
    allCaughtUp: 'सब अपडेट है!',
    noNotifications: 'यहाँ कोई सूचना नहीं',
    markAsRead: 'पढ़ा हुआ चिह्नित करें',
    clearAll: 'सब साफ करें',
    profile: 'प्रोफ़ाइल',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    businessDetails: 'व्यवसाय विवरण',
    legalEntity: 'कानूनी संस्था',
    establishmentDate: 'स्थापना तिथि',
    registeredAddress: 'पंजीकृत पता',
    gstCompliance: 'GST अनुपालन',
    savedDeliverySites: 'सहेजी गई डिलीवरी साइटें',
    languageSection: 'भाषा / Language',
    english: 'English',
    englishSubtitle: 'Use app in English',
    hindi: 'हिंदी',
    hindiSubtitle: 'ऐप हिंदी में उपयोग करें',
    languageNote: 'ऑर्डर, चालान, सूचनाएं और वॉयस सर्च आपकी चुनी हुई भाषा में होंगे।',
    orderHistoryMenu: 'ऑर्डर इतिहास',
    invoices: 'चालान',
    loyaltyWallet: 'लॉयल्टी वॉलेट',
    privacySecurity: 'गोपनीयता और सुरक्षा',
    logout: 'लॉग आउट',
    logoutConfirm: 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    paymentMethods: 'भुगतान विधियाँ',
    primary: 'प्राथमिक',
    platinumMember: 'प्लेटिनम सदस्य',
    personalDetails: 'व्यक्तिगत विवरण',
    fullName: 'पूरा नाम',
    mobileNumber: 'मोबाइल नंबर',
    emailAddress: 'ईमेल पता',
    gstNumberLabel: 'GST नंबर',
    businessProfile: 'व्यवसाय प्रोफ़ाइल',
    businessType: 'व्यवसाय प्रकार',
    procurement: 'खरीद',
    city: 'शहर',
    activeProjectSites: 'सक्रिय प्रोजेक्ट साइटें',
    addNewSite: '+ नई साइट जोड़ें',
    saveAllChanges: 'सभी बदलाव सहेजें',
    cancelChanges: 'बदलाव रद्द करें',
    deliverySites: 'डिलीवरी साइटें',
    addNewProjectSite: '+ नई प्रोजेक्ट साइट जोड़ें',
    warehouseDist: 'गोदाम दूरी',
    estDelivery: 'अनुमानित डिलीवरी',
    siteName: 'साइट का नाम',
    contactPerson: 'संपर्क व्यक्ति',
    fullAddress: 'पूरा पता',
    pincode: 'पिनकोड',
    gateInstructions: 'गेट निर्देश (वैकल्पिक)',
    saveSite: 'साइट सहेजें',
    businessVerification: 'व्यवसाय सत्यापन',
    gstVerified: 'GST सत्यापित',
    complianceScore: 'अनुपालन स्कोर',
    entityInformation: 'संस्था जानकारी',
    pan: 'PAN',
    registrationDate: 'पंजीकरण तिथि',
    jurisdiction: 'अधिकार क्षेत्र',
    gstCertificate: 'GST प्रमाण पत्र',
    downloadPdf: 'PDF डाउनलोड करें',
    invoicesTitle: 'चालान',
    searchInvoice: 'चालान आईडी, साइट या विक्रेता खोजें',
    all: 'सभी',
    unpaid: 'अवैतनिक',
    overdue: 'अतिदेय',
    totalAmountLabel: 'कुल राशि',
    viewTimeline: 'समयरेखा देखें',
    syncGstTitle: 'GST रिटर्न समन्वयित करें',
    syncGstSubtitle: 'Tally या ERP सॉफ़्टवेयर को Bajriwala से जोड़कर GSTR-1 और GSTR-3B स्वचालित करें।',
    connectErp: 'ERP कनेक्ट करें',
    loyaltyRewards: 'लॉयल्टी रिवॉर्ड',
    premiumTier: 'प्रीमियम स्तर',
    platinumContractorTitle: 'प्लेटिनम\nठेकेदार',
    totalPoints: 'कुल पॉइंट',
    cashbackEarned: 'अर्जित कैशबैक',
    membershipProgress: 'सदस्यता प्रगति',
    spendMore: 'डायमंड तक पहुंचने के लिए ₹1.2L और खर्च करें',
    totalSpend: 'कुल खर्च',
    diamondTier: 'डायमंड स्तर',
    viewTierBenefits: 'स्तर लाभ देखें',
    proKnight: 'प्रो नाइट',
    earn2xPoints: 'स्टील पर 2x पॉइंट अर्जित करें',
    earn2xSubtitle: 'इस सप्ताह 50 मीट्रिक टन Tata Tiscon ऑर्डर करके डबल माइलस्टोन क्रेडिट अनलॉक करें।',
    redeemRewardsTitle: 'रिवॉर्ड रिडीम करें',
    redeemSubtitle: 'आपके प्रोजेक्ट के लिए प्रीमियम लाभ',
    hotDeal: 'बेस्ट डील',
    platinumOnly: 'केवल प्लेटिनम',
    canRedeem: '✓ आप यह रिडीम कर सकते हैं',
    needMoreCP: 'और CP चाहिए',
    activityHistory: 'गतिविधि इतिहास',
    downloadStatement: 'स्टेटमेंट डाउनलोड करें',
    supportDisputes: 'सहायता और विवाद',
    history: 'इतिहास',
    newTicket: '+ नया टिकट',
    activeDispute: 'सक्रिय विवाद',
    inReview: 'समीक्षा में',
    resolutionSteps: 'समाधान चरण',
    ticketRaised: 'टिकट दर्ज',
    evidenceReceived: 'साक्ष्य प्राप्त',
    underInvestigation: 'जांच में',
    resolutionPending: 'समाधान लंबित',
    fileNewDispute: 'नया विवाद दर्ज करें',
    reportWrongItem: 'गलत आइटम की रिपोर्ट',
    damagedGoods: 'क्षतिग्रस्त माल',
    missingQuantity: 'कम मात्रा',
    refundRequest: 'धनवापसी अनुरोध',
    uploadEvidence: 'साक्ष्य अपलोड करें',
    uploadEvidenceSubtitle: 'क्षतिग्रस्त वस्तुओं की उच्च-रिज़ॉल्यूशन फ़ोटो या वीडियो प्रदान करें।',
    dragDropFiles: 'मीडिया फ़ाइलें यहाँ खींचें',
    supportsFormats: 'JPG, PNG, MP4 50MB तक समर्थित',
    selectFiles: 'फ़ाइलें चुनें',
    liveChat: 'लाइव चैट',
    liveChatSubtitle: '2 मिनट में जवाब',
    callSupportLabel: 'सहायता कॉल',
    callSupportSubtitle: 'डायरेक्ट लाइन उपलब्ध',
    voiceAssistant: 'वॉयस असिस्टेंट',
    activeConnection: 'सक्रिय कनेक्शन',
    tapToSpeak: 'बोलने के लिए टैप करें',
    listening: 'सुन रहे हैं...',
    findingResults: 'परिणाम खोज रहे हैं...',
    hereIsWhatIFound: 'यह मिला मुझे',
    trySaying: 'कहकर देखें',
    orderCementBags: 'सीमेंट बैग ऑर्डर करें',
    steelPricesToday: 'आज स्टील की कीमत',
    trackMyOrder: 'मेरा ऑर्डर ट्रैक करें',
    emergencyDelivery: 'आपातकालीन डिलीवरी',
    result: 'परिणाम',
    tryAgain: 'फिर कोशिश करें',
    searchTitle: 'खोज',
    searchBajriwala: 'Bajriwala में खोजें',
    recentSearches: 'हाल की खोजें',
    searchResults: 'खोज परिणाम',
    frequentlyPurchasedTogether: 'अक्सर एक साथ खरीदे जाते हैं',
    recentlyViewed: 'हाल ही में देखे गए',
    noResultsFor: 'कोई परिणाम नहीं',
    trySearching: 'सीमेंट, स्टील, रेत, ईंट खोजें',
    trySearchingFor: 'इन्हें खोजकर देखें:',
    popularCategories: 'लोकप्रिय श्रेणियाँ',
    resultsFor: 'परिणाम',
    sortBy: 'क्रमबद्ध करें',
    relevance: 'प्रासंगिकता',
    priceLowHigh: 'कीमत: कम से अधिक',
    priceHighLow: 'कीमत: अधिक से कम',
    newestFirst: 'नवीनतम पहले',
    oldestFirst: 'सबसे पुराना पहले',
    nameAZ: 'नाम: A से Z',
    browseAllCategories: 'सभी श्रेणियाँ देखें →',
    completeProfileTitle: 'अपनी प्रोफ़ाइल पूरी करें',
    completeProfileSubtitle: 'शुरू करने के लिए अपना नाम और पसंदीदा भाषा बताएं।',
    companyName: 'कंपनी का नाम',
    companyNamePlaceholder: 'अपनी कंपनी का नाम दर्ज करें',
    gstPlaceholder: '22AAAAA0000A1Z5',
    chooseLanguage: 'अपनी पसंदीदा भाषा चुनें',
    languageSubtitle: 'उस भाषा में जारी रखें जिसमें आप सबसे सहज हैं।',
    hindiLink: 'अपनी पसंदीदा भाषा चुनें',
    recommendedRegion: 'आपके क्षेत्र के आधार पर अनुशंसित',
    continueInEnglish: 'Continue in English',
    continueInHindi: 'हिंदी में जारी रखें',
    isoSecurity: 'ISO 27001 प्रमाणित एंटरप्राइज़ सुरक्षा',
    continueBtn: 'जारी रखें',
    deliveryLocation: 'डिलीवरी स्थान',
    searchSiteAddress: 'साइट का पता खोजें',
    preciseGpsPinning: 'सटीक GPS पिनिंग',
    manageProjects: 'अपनी सक्रिय निर्माण परियोजनाओं का प्रबंधन करें',
    registerDeliveryPoint: 'एक नया डिलीवरी पॉइंट पंजीकृत करें',
    industrialPrecision: 'औद्योगिक सटीकता',
    industrialPrecisionDesc: 'हमारी प्रणाली उच्च-सटीकता जियो-फेंसिंग का उपयोग करती है ताकि सामग्री ठीक वहीं पहुंचे जहां आपकी टीम को जरूरत है।',
    siteLogisticsSupport: 'साइट लॉजिस्टिक्स सहायता',
    siteLogisticsSupportDesc: 'विशिष्ट गेट प्रवेश निर्देश चाहिए? अपनी साइट प्रोफ़ाइल में जोड़ें और हमारे ड्राइवर हर प्रोटोकॉल का पालन करेंगे।',
    allowFetchLocation: 'स्थान अनुमति दें',
    addressLine1: 'पता पंक्ति 1',
    drawerHome: 'होम',
    drawerCatalog: 'उत्पाद कैटलॉग',
    drawerOrders: 'मेरे ऑर्डर',
    drawerTrackDeliveries: 'डिलीवरी ट्रैक करें',
    drawerSavedSites: 'सहेजी गई साइटें',
    drawerGstInvoices: 'जीएसटी चालान',
    drawerLoyalty: 'लॉयल्टी और पुरस्कार',
    drawerNotifications: 'सूचनाएं',
    drawerProcurementTools: 'खरीदारी उपकरण',
    drawerEmergencyOrders: 'आपातकालीन ऑर्डर',
    drawerBulkProcurement: 'थोक खरीदारी',
    drawerOrderHistory: 'ऑर्डर इतिहास',
    drawerSupport: 'सहायता',
    drawerHelpCenter: 'सहायता केंद्र',
    drawerWhatsAppSupport: 'व्हाट्सएप सहायता',
    drawerRaiseTicket: 'टिकट बनाएं',
    drawerPreferences: 'प्राथमिकताएं',
    drawerLanguage: 'भाषा',
    drawerPrivacy: 'गोपनीयता और सुरक्षा',
    drawerTerms: 'नियम और शर्तें',
    drawerLogout: 'लॉगआउट',
    drawerVersion: 'Bajriwala v2.4.0',
    drawerLogoutTitle: 'लॉगआउट',
    drawerLogoutMessage: 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
    drawerLogoutConfirm: 'लॉगआउट',
    drawerLogoutCancel: 'रद्द करें',
    filterOrders: 'ऑर्डर फ़िल्टर करें',
    filterStatus: 'स्थिति',
    filterDate: 'तिथि',
    filterAll: 'सभी',
    filterActive: 'सक्रिय',
    filterDelivered: 'डिलीवर',
    filterCancelled: 'रद्द',
    filterAllTime: 'सभी समय',
    filterToday: 'आज',
    filterThisWeek: 'इस सप्ताह',
    filterThisMonth: 'इस महीने',
    apply: 'लागू करें',
    minUnits: 'न्यून. {{count}} इकाइयाँ',
    goBack: 'वापस जाएं',
    productNotFound: 'उत्पाद नहीं मिला',
    noProductsFound: 'कोई उत्पाद नहीं मिला',
    unableToLoadProducts: 'उत्पाद लोड नहीं हो सके।',
    unableToLoadCategories: 'श्रेणियाँ लोड नहीं हो सकीं।',
    locationAccessRequired: 'स्थान पहुंच आवश्यक है',
    bulkProcurement: 'थोक खरीदारी',
    goldMember: 'गोल्ड सदस्य',
    silverMember: 'सिल्वर सदस्य',
    scheduledDeliveryLabel: 'निर्धारित डिलीवरी',
    etaLabel: 'अनुमानित समय',
    orderedStep: 'ऑर्डर किया',
    processingStep: 'प्रक्रिया में',
    shippingStep: 'शिपिंग',
    deliveryStep: 'डिलीवरी',
    confirmed: 'पुष्टि हो गई',
    catalogLabel: 'कैटलॉग',
    applied: 'लागू',
    maxLabel: 'अधिकतम',
    loyaltyRedemption: 'लॉयल्टी रिडemption',
    addPaymentMethod: 'भुगतान विधि जोड़ें',
    contactLink: 'संपर्क',
    readAction: 'पढ़ें',
    markRead: 'पढ़ा हुआ चिह्नित करें',
    proTipEfficiencyTitle: 'खरीदारी दक्षता बढ़ाएं',
    proTipEfficiencyBody: 'डिलीवरी शुल्क कम करने और थोक मूल्य स्तर अनलॉक करने के लिए एक ही गोदाम से ऑर्डर एक साथ करें।',
    privacyBiometric: 'बायोमेट्रिक लॉगिन',
    privacyBiometricDesc: 'Face ID या फिंगरप्रिंट से अपना खाता सुरक्षित करें',
    privacyTwoFactor: 'दो-कारक प्रमाणीकरण',
    privacyTwoFactorDesc: 'OTP सत्यापन के साथ अतिरिक्त सुरक्षा जोड़ें',
    privacyAnalytics: 'उपयोग विश्लेषण',
    privacyAnalyticsDesc: 'अनाम उपयोग डेटा साझा करके हमें सुधारने में मदद करें',
    privacyDataTitle: 'डेटा और गोपनीयता',
    privacyDataBody: 'आपका व्यवसाय डेटा एन्क्रिप्टेड है और सहमति के बिना कभी तीसरे पक्ष के साथ साझा नहीं किया जाता।',
    invoiceDetails: 'चालान विवरण',
    billedFrom: 'बिल से',
    billedTo: 'बिल को',
    itemsOrdered: 'ऑर्डर की गई वस्तुएं',
    timeline: 'समयरेखा',
    downloadPdfShort: 'PDF डाउनलोड करें',
    termsSection: 'नियम और शर्तें',
    trackDeliveries: 'डिलीवरी ट्रैक करें',
    trackDeliveriesEmpty: 'ट्रैक करने के लिए कोई सक्रिय डिलीवरी नहीं',
    loyaltyRewardsTitle: 'लॉयल्टी पुरस्कार',
    availablePoints: 'उपलब्ध अंक',
    walletBalance: 'वॉलेट बैलेंस',
    recentActivity: 'हाल की गतिविधि',
    addPaymentMethodLabel: 'भुगतान विधि जोड़ें',
    invoiceGenerated: 'चालान बनाया गया',
    paymentReceived: 'भुगतान प्राप्त',
    gstFiled: 'GST दाखिल',
    whatsapp: 'व्हाट्सएप',
    pdf: 'PDF',
    paidFilter: 'भुगतान हो गया',
    contactPersonLabel: 'संपर्क व्यक्ति',
    editDeliverySite: 'डिलीवरी साइट संपादित करें',
    editProjectSite: 'प्रोजेक्ट साइट संपादित करें',
    pinLocation: 'स्थान पिन करें',
    cancelLabel: 'रद्द करें',
    profileSaved: 'प्रोफ़ाइल सहेजी गई',
    comingSoon: 'जल्द आ रहा है',
    online: 'ऑनलाइन',
    chatPlaceholder: 'चैट शुरू करने के लिए नीचे संदेश लिखें',
    splashTagline: 'निर्माण सामग्री\nतेज़ डिलीवरी',
    enterpriseSecureNetwork: 'एंटरप्राइज़ सुरक्षित नेटवर्क',
    welcomeBack: 'वापस स्वागत है, बिल्डर',
    loginSubtitle: 'साइट लॉजिस्टिक्स और खरीदारी प्रबंधित करने के लिए अपना मोबाइल नंबर दर्ज करें।',
    loginMobileLabel: 'मोबाइल नंबर',
    loginBtn: 'लॉगिन',
    trustedBy: 'दिल्ली के 500+ ठेकेदारों का भरोसा',
    contractorsIndia: 'दिल्ली भर के ठेकेदार',
    helpCenter: 'सहायता केंद्र',
    privacyPolicy: 'गोपनीयता नीति',
    termsLink: 'नियम',
    copyrightNotice: '© 2024 Bajriwala India Private Limited. सर्वाधिकार सुरक्षित।',
    verifyIdentity: 'अपनी पहचान सत्यापित करें',
    otpSentTo: 'हमने 6-अंकीय कोड भेजा है',
    changeNumber: 'नंबर बदलें',
    resendCodeIn: 'कोड पुनः भेजें',
    verifyContinue: 'सत्यापित करें और जारी रखें',
    secureEncryption: 'सुरक्षित 256-बिट AES एन्क्रिप्शन',
    selectRole: 'अपनी भूमिका चुनें',
    personalizeExperience: 'अपने बजरीप्रो अनुभव को वैयक्तिकृत करें',
    roleIndividual: 'व्यक्तिगत',
    roleIndividualDesc: 'व्यक्तिगत या घरेलू परियोजनाओं के लिए सामग्री ऑर्डर करें।',
    roleContractor: 'ठेकेदार',
    roleContractorDesc: 'साइट लॉजिस्टिक्स, श्रम और खरीदारी प्रबंधित करें।',
    roleInterior: 'इंटीरियर डिज़ाइनर / वास्तुकार',
    roleInteriorDesc: 'प्रीमियम सामग्री प्राप्त करें और इंटीरियर प्रबंधित करें।',
    roleBuilder: 'बिल्डर / डेवलपर',
    roleBuilderDesc: 'बड़े पैमाने पर निर्माण और परियोजनाएं संभालें।',
    redeemPointsNextOrder: 'अगले ऑर्डर पर पॉइंट रिडीम करें',
    totalAmountPayable: 'कुल देय राशि',
    inclusiveTaxes: 'सभी करों सहित',
    shareOnWhatsAppShort: 'WhatsApp पर साझा करें',
    loyaltyPointsProgress: '450 / 600 pts',
    lastOrderedTmt: 'अंतिम ऑर्डर: 3 दिन पहले',
    lastOrderedPvc: 'अंतिम ऑर्डर: 1 सप्ताह पहले',
  },
} as const;

export type StringKeys = keyof typeof strings.en;
export type StringKey = StringKeys;
